import { saveAs } from "file-saver";
import { toPng } from "html-to-image";
import type { Options } from "html-to-image/lib/types";
import JSZip from "jszip";
import {
	type Edge,
	getNodesBounds,
	getViewportForBounds,
	type Node,
} from "reactflow";
import {
	type BrandingConfig,
	createTemplateFromPreset,
	type DiagramImage,
	type ExportFormat,
	exporterRegistry,
	type TemplatePreset,
} from "@/lib/export";
import type { LabelledDiagramImage, TemplateInput } from "@/lib/export/types";
import type { CaseExportNested } from "@/lib/schemas/case-export";
import { extractBranches } from "./branch-utils";
import type { LayoutDirection } from "./layout-helper";
import { getLayoutedElements } from "./layout-helper";

const DATA_URL_PREFIX_REGEX = /^data:image\/png;base64,/;
const MARKDOWN_EXTENSION_REGEX = /\.md$/;

/** Landscape A4 aspect ratio (width / height = sqrt(2)) */
const LANDSCAPE_A4_RATIO = Math.SQRT2;

/** Compact spacing values for export layouts */
const EXPORT_NODE_SPACING = 25;
const EXPORT_LAYER_SPACING = 40;

/** Node count threshold above which branch diagrams are auto-suggested */
export const BRANCH_DIAGRAM_THRESHOLD = 15;

/**
 * TEA Platform brand colour (matches the application theme).
 */
const TEA_PRIMARY_COLOUR = "#1e3a5f";

/**
 * Fetch an image from a URL and convert to base64 data URL.
 */
async function fetchImageAsBase64(url: string): Promise<string | undefined> {
	try {
		const response = await fetch(url);
		if (!response.ok) {
			return;
		}
		const blob = await response.blob();
		return new Promise((resolve) => {
			const reader = new FileReader();
			reader.onloadend = () => resolve(reader.result as string);
			reader.onerror = () => resolve(undefined);
			reader.readAsDataURL(blob);
		});
	} catch {
		return;
	}
}

/**
 * Get default TEA Platform branding with logo.
 */
async function getDefaultBranding(): Promise<Partial<BrandingConfig>> {
	const logoBase64 = await fetchImageAsBase64(
		"/images/logos/tea-logo-full-light.png"
	);

	return {
		primaryColour: TEA_PRIMARY_COLOUR,
		logoBase64,
		organisationName: "TEA Platform",
		footerText: "Generated by TEA Platform",
	};
}

export type DiagramMode = "single" | "branches";

export type LayoutApplyFn = (
	layoutNodes: Node[],
	layoutEdges: Edge[],
	direction?: LayoutDirection
) => void;

export type DocumentExportOptions = {
	caseData: CaseExportNested;
	caseName: string;
	format: ExportFormat;
	template: TemplatePreset;
	includeDiagram: boolean;
	nodes: Node[];
	edges: Edge[];
	layoutDirection: LayoutDirection;
	applyLayout: LayoutApplyFn;
	restoreLayout: () => void;
	sectionOverrides?: Record<string, boolean>;
	maxDiagramDepth?: number | null;
	diagramMode?: DiagramMode;
};

/**
 * Filter function for diagram capture - exclude UI controls.
 */
function shouldIncludeInDiagram(domNode: HTMLElement): boolean {
	if (!(domNode instanceof Element)) {
		return true;
	}
	const classList = domNode.classList;
	if (!classList) {
		return true;
	}
	return !(
		classList.contains("react-flow__minimap") ||
		classList.contains("react-flow__controls") ||
		classList.contains("react-flow__panel") ||
		classList.contains("react-flow__attribution")
	);
}

/**
 * Apply inline styles to edges for export.
 * Returns cleanup function to restore original styles.
 */
function applyExportStyles(viewport: HTMLElement): () => void {
	const edgePaths = viewport.querySelectorAll(".react-flow__edge-path");
	const originalStyles: Map<Element, { stroke: string; strokeWidth: string }> =
		new Map();

	for (const path of edgePaths) {
		const svgPath = path as SVGElement;
		originalStyles.set(path, {
			stroke: svgPath.getAttribute("stroke") || "",
			strokeWidth: svgPath.getAttribute("stroke-width") || "",
		});
		svgPath.setAttribute("stroke", "#666666");
		svgPath.setAttribute("stroke-width", "2");
	}

	return () => {
		for (const path of edgePaths) {
			const svgPath = path as SVGElement;
			const original = originalStyles.get(path);
			if (original) {
				if (original.stroke) {
					svgPath.setAttribute("stroke", original.stroke);
				} else {
					svgPath.removeAttribute("stroke");
				}
				if (original.strokeWidth) {
					svgPath.setAttribute("stroke-width", original.strokeWidth);
				} else {
					svgPath.removeAttribute("stroke-width");
				}
			}
		}
	};
}

/**
 * Collect a fingerprint of every edge SVG path currently in the DOM.
 * Used to detect when React Flow has finished recalculating edge routes.
 */
function edgePathFingerprint(): string {
	const paths = document.querySelectorAll(".react-flow__edge-path");
	return Array.from(paths)
		.map((el) => (el as SVGPathElement).getAttribute("d") ?? "")
		.join("|");
}

/**
 * Wait for React Flow to fully settle after a layout swap.
 *
 * Two rAFs ensure React has committed the state update and flushed effects
 * (including the updateNodeInternals call in flow.tsx). Then we poll edge
 * SVG paths until two consecutive reads match — meaning node handles have
 * repositioned and edge paths have finished recalculating.
 *
 * Falls back to a maximum wait of ~2 s to prevent hanging.
 */
export async function waitForRender(): Promise<void> {
	// Double rAF: React commits the state update + useEffect fires
	await new Promise<void>((resolve) => {
		requestAnimationFrame(() => {
			requestAnimationFrame(() => resolve());
		});
	});

	// Poll for edge path stability
	const maxAttempts = 20;
	const intervalMs = 100;
	let previous = edgePathFingerprint();

	for (let i = 0; i < maxAttempts; i++) {
		await new Promise<void>((r) => setTimeout(r, intervalMs));
		const current = edgePathFingerprint();
		if (current === previous) {
			return;
		}
		previous = current;
	}
}

/**
 * Build a map of parent → children from edges.
 */
function buildChildrenMap(edges: Edge[]): Map<string, string[]> {
	const parentToChildren = new Map<string, string[]>();
	for (const edge of edges) {
		const children = parentToChildren.get(edge.source) ?? [];
		children.push(edge.target);
		parentToChildren.set(edge.source, children);
	}
	return parentToChildren;
}

/**
 * Find root nodes in a graph (nodes with no incoming edges from within the set).
 */
function findRootNodes(nodes: Node[], edges: Edge[]): Node[] {
	const nodeIds = new Set(nodes.map((n) => n.id));
	const hasInternalParent = new Set<string>();

	for (const edge of edges) {
		if (nodeIds.has(edge.source) && nodeIds.has(edge.target)) {
			hasInternalParent.add(edge.target);
		}
	}

	return nodes.filter((n) => !hasInternalParent.has(n.id));
}

/**
 * BFS to compute depth of each node from the given roots.
 */
function computeDepthMap(
	roots: Node[],
	childrenMap: Map<string, string[]>
): Map<string, number> {
	const depthMap = new Map<string, number>();
	const queue: Array<{ id: string; depth: number }> = [];

	for (const root of roots) {
		depthMap.set(root.id, 0);
		queue.push({ id: root.id, depth: 0 });
	}

	while (queue.length > 0) {
		const current = queue.shift();
		if (!current) {
			break;
		}
		const children = childrenMap.get(current.id) ?? [];
		for (const childId of children) {
			if (!depthMap.has(childId)) {
				depthMap.set(childId, current.depth + 1);
				queue.push({ id: childId, depth: current.depth + 1 });
			}
		}
	}

	return depthMap;
}

/**
 * Prune nodes and edges to only include elements within a given depth.
 */
export function pruneByDepth(
	nodes: Node[],
	edges: Edge[],
	maxDepth: number
): { nodes: Node[]; edges: Edge[] } {
	const roots = findRootNodes(nodes, edges);
	const childrenMap = buildChildrenMap(edges);
	const depthMap = computeDepthMap(roots, childrenMap);

	const allowedIds = new Set<string>();
	for (const [id, depth] of depthMap) {
		if (depth <= maxDepth) {
			allowedIds.add(id);
		}
	}

	return {
		nodes: nodes.filter((n) => allowedIds.has(n.id)),
		edges: edges.filter(
			(e) => allowedIds.has(e.source) && allowedIds.has(e.target)
		),
	};
}

/**
 * Determine optimal layout direction for export based on diagram aspect ratio.
 * If the diagram is wider than a landscape A4 page, switch to LR direction.
 */
function chooseExportDirection(
	nodes: Node[],
	currentDirection: LayoutDirection
): LayoutDirection {
	if (nodes.length === 0) {
		return currentDirection;
	}

	const bounds = getNodesBounds(nodes);
	const aspectRatio = bounds.width / Math.max(bounds.height, 1);

	if (aspectRatio > LANDSCAPE_A4_RATIO) {
		return "LR";
	}

	return currentDirection;
}

/**
 * Create an export layout with auto-LR direction detection.
 *
 * By default uses compact spacing for document embeds. Pass custom spacing
 * values (e.g. the ELK defaults of 40/60) for standalone image exports
 * where edge clarity matters more than compactness.
 */
export async function layoutForExport(
	nodes: Node[],
	edges: Edge[],
	currentDirection: LayoutDirection,
	spacing?: { nodeSpacing?: number; layerSpacing?: number }
): Promise<{ nodes: Node[]; edges: Edge[]; direction: LayoutDirection }> {
	const direction = chooseExportDirection(nodes, currentDirection);

	const { nodes: layoutedNodes, edges: layoutedEdges } =
		await getLayoutedElements(nodes, edges, {
			direction,
			nodeSpacing: spacing?.nodeSpacing ?? EXPORT_NODE_SPACING,
			layerSpacing: spacing?.layerSpacing ?? EXPORT_LAYER_SPACING,
		});

	return { nodes: layoutedNodes, edges: layoutedEdges, direction };
}

/**
 * Capture the diagram as a base64-encoded PNG for embedding in documents.
 */
async function captureDiagramImage(
	nodes: Node[]
): Promise<DiagramImage | null> {
	const viewport = document.querySelector(
		".react-flow__viewport"
	) as HTMLElement | null;

	if (!viewport || nodes.length === 0) {
		return null;
	}

	const visibleNodes = nodes.filter(
		(n) => !(n as Node & { hidden?: boolean }).hidden
	);
	if (visibleNodes.length === 0) {
		return null;
	}

	const nodesBounds = getNodesBounds(visibleNodes);
	const padding = 100;
	const imageWidth = nodesBounds.width + padding * 2;
	const imageHeight = nodesBounds.height + padding * 2;

	const transform = getViewportForBounds(
		nodesBounds,
		imageWidth,
		imageHeight,
		0.5,
		2
	);

	const exportOptions: Options = {
		backgroundColor: "#ffffff",
		width: imageWidth,
		height: imageHeight,
		style: {
			width: `${imageWidth}px`,
			height: `${imageHeight}px`,
			transform: `translate(${transform.x}px, ${transform.y}px) scale(${transform.zoom})`,
		},
		filter: shouldIncludeInDiagram,
		cacheBust: true,
		pixelRatio: 2,
	};

	const restoreStyles = applyExportStyles(viewport);

	try {
		const dataUrl = await toPng(viewport, exportOptions);
		const base64Data = dataUrl.replace(DATA_URL_PREFIX_REGEX, "");
		return { data: base64Data, format: "png" };
	} finally {
		restoreStyles();
	}
}

/**
 * Capture per-branch diagram images for multi-page exports.
 * Each direct child of the root node produces one branch diagram.
 */
async function captureBranchDiagrams(
	sourceNodes: Node[],
	sourceEdges: Edge[],
	applyLayout: LayoutApplyFn,
	restoreLayout: () => void,
	layoutDirection: LayoutDirection
): Promise<LabelledDiagramImage[]> {
	const branches = extractBranches(sourceNodes, sourceEdges);
	if (branches.length === 0) {
		return [];
	}

	const results: LabelledDiagramImage[] = [];

	try {
		for (const branch of branches) {
			// Create nodes/edges with non-branch elements hidden
			const branchNodes = sourceNodes.map((n) => ({
				...n,
				hidden: !branch.nodeIds.has(n.id),
			}));
			const branchEdges = sourceEdges.map((e) => ({
				...e,
				hidden: !(branch.nodeIds.has(e.source) && branch.nodeIds.has(e.target)),
			}));

			// Layout only the visible branch nodes
			const {
				nodes: layoutedNodes,
				edges: layoutedEdges,
				direction,
			} = await layoutForExport(branchNodes, branchEdges, layoutDirection);

			// Push to DOM (including direction for correct handle positioning)
			applyLayout(layoutedNodes, layoutedEdges, direction);
			await waitForRender();

			const captured = await captureDiagramImage(layoutedNodes);
			if (captured) {
				results.push({
					...captured,
					title: branch.label,
				});
			}
		}
	} finally {
		restoreLayout();
		await waitForRender();
	}

	return results;
}

/**
 * Export an assurance case as a document (PDF, Word, or Markdown).
 *
 * This function orchestrates the full export flow:
 * 1. Optionally applies compact export layout with auto-LR direction
 * 2. Optionally prunes by depth
 * 3. Captures the diagram as an image (and branch diagrams if requested)
 * 4. Creates a template from the selected preset
 * 5. Renders the document using the template
 * 6. Exports to the specified format
 * 7. Downloads the result
 */
export async function exportDocument(
	options: DocumentExportOptions
): Promise<void> {
	const {
		caseData,
		caseName,
		format,
		template,
		includeDiagram,
		nodes,
		edges,
		layoutDirection,
		applyLayout,
		restoreLayout,
		sectionOverrides,
		maxDiagramDepth,
		diagramMode = "single",
	} = options;

	let diagramImage: DiagramImage | undefined;
	let branchDiagrams: LabelledDiagramImage[] | undefined;

	if (includeDiagram) {
		// Prepare nodes/edges for export (optionally pruned by depth)
		let exportNodes = nodes.map((n) => ({ ...n }));
		let exportEdges = edges.map((e) => ({ ...e }));

		if (maxDiagramDepth != null) {
			const pruned = pruneByDepth(exportNodes, exportEdges, maxDiagramDepth);
			exportNodes = pruned.nodes;
			exportEdges = pruned.edges;
		}

		// Apply compact export layout
		const {
			nodes: layoutedNodes,
			edges: layoutedEdges,
			direction,
		} = await layoutForExport(exportNodes, exportEdges, layoutDirection);

		// Push export layout to DOM (including direction for correct handle positioning)
		applyLayout(layoutedNodes, layoutedEdges, direction);
		await waitForRender();

		const captured = await captureDiagramImage(layoutedNodes);
		if (captured) {
			diagramImage = captured;
		}

		// Restore before branch capture (branch capture does its own layout swaps)
		restoreLayout();
		await waitForRender();

		// Capture branch diagrams if requested
		if (diagramMode === "branches") {
			branchDiagrams = await captureBranchDiagrams(
				exportNodes,
				exportEdges,
				applyLayout,
				restoreLayout,
				layoutDirection
			);
		}
	}

	// Get default TEA branding with logo
	const branding = await getDefaultBranding();

	// Create template from preset with branding
	const templateInstance = createTemplateFromPreset(template, branding);

	// Render the document with section overrides
	const templateInput: TemplateInput = {
		caseData,
		diagramImage,
		branchDiagrams,
		sectionOverrides,
	};
	const renderedDocument = await templateInstance.render(templateInput);

	// Get the appropriate exporter
	const exporter = exporterRegistry.get(format);
	if (!exporter) {
		throw new Error(`No exporter available for format: ${format}`);
	}

	// Export to format
	const result = await exporter.export(renderedDocument, {
		caseName,
		timestamp: new Date(),
	});

	if (!result.success) {
		throw new Error(result.error);
	}

	// Handle markdown with diagram - create ZIP archive
	if (
		format === "markdown" &&
		includeDiagram &&
		diagramImage &&
		"content" in result
	) {
		await exportMarkdownZip(
			result.content,
			result.filename,
			diagramImage,
			branchDiagrams
		);
		return;
	}

	// Download the result
	if ("blob" in result) {
		saveAs(result.blob, result.filename);
	} else if ("content" in result) {
		const blob = new Blob([result.content], { type: result.mimeType });
		saveAs(blob, result.filename);
	}
}

/**
 * Convert base64 string to Uint8Array.
 */
function base64ToUint8Array(base64: string): Uint8Array {
	const binaryData = atob(base64);
	const uint8Array = new Uint8Array(binaryData.length);
	for (let i = 0; i < binaryData.length; i++) {
		uint8Array[i] = binaryData.charCodeAt(i);
	}
	return uint8Array;
}

/**
 * Export markdown with diagram as a ZIP archive.
 *
 * Creates a ZIP containing:
 * - report.md - the markdown file with relative image reference
 * - diagram.png - the overview diagram image
 * - branch-N-*.png - optional branch diagram images
 */
async function exportMarkdownZip(
	markdownContent: string,
	markdownFilename: string,
	diagramImage: DiagramImage,
	branchDiagrams?: LabelledDiagramImage[]
): Promise<void> {
	const zip = new JSZip();

	zip.file(markdownFilename, markdownContent);
	zip.file("diagram.png", base64ToUint8Array(diagramImage.data));

	if (branchDiagrams) {
		for (const [i, branch] of branchDiagrams.entries()) {
			const safeName = branch.title
				.toLowerCase()
				.replace(/[^a-z0-9]+/g, "-")
				.replace(/^-|-$/g, "");
			zip.file(
				`branch-${i + 1}-${safeName}.png`,
				base64ToUint8Array(branch.data)
			);
		}
	}

	const zipBlob = await zip.generateAsync({ type: "blob" });
	const zipFilename = markdownFilename.replace(
		MARKDOWN_EXTENSION_REGEX,
		".zip"
	);
	saveAs(zipBlob, zipFilename);
}
