# Generated by Django 3.2.8 on 2021-10-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.CharField(max_length=3000)),
                ('shape', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AssuranceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('shape', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TopLevelNormativeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.CharField(max_length=3000)),
                ('keywords', models.CharField(max_length=3000)),
                ('shape', models.IntegerField(default=0)),
                ('assurance_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eap_api.assurancecase')),
            ],
        ),
        migrations.CreateModel(
            name='SystemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.CharField(max_length=3000)),
                ('shape', models.IntegerField(default=0)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eap_api.toplevelnormativegoal')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.CharField(max_length=3000)),
                ('shape', models.IntegerField(default=0)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eap_api.toplevelnormativegoal')),
            ],
        ),
        migrations.CreateModel(
            name='EvidentialClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.CharField(max_length=3000)),
                ('shape', models.IntegerField(default=0)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eap_api.argument')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.CharField(max_length=3000)),
                ('URL', models.CharField(max_length=3000)),
                ('shape', models.IntegerField(default=0)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eap_api.evidentialclaim')),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.CharField(max_length=3000)),
                ('shape', models.IntegerField(default=0)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eap_api.toplevelnormativegoal')),
            ],
        ),
        migrations.AddField(
            model_name='argument',
            name='goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eap_api.propertyclaim'),
        ),
    ]
