# Generated by Django 3.2.8 on 2021-10-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eap_api', '0003_auto_20211026_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argument',
            name='property_claim_id',
        ),
        migrations.AddField(
            model_name='argument',
            name='property_claim_id',
            field=models.ManyToManyField(to='eap_api.PropertyClaim'),
        ),
    ]
