# Generated by Django 3.2.8 on 2021-11-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eap_api', '0004_auto_20211026_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argument',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='assurancecase',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='context',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='evidentialclaim',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='propertyclaim',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='systemdescription',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='toplevelnormativegoal',
            name='shape',
        ),
    ]
