# Generated by Django 3.2.8 on 2023-09-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eap_api", "0005_alter_eapuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eapuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="property_claim",
            field=models.ManyToManyField(
                related_name="evidence", to="eap_api.PropertyClaim"
            ),
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "long_description",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to="eap_api.toplevelnormativegoal",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="propertyclaim",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategy",
                to="eap_api.strategy",
            ),
        ),
    ]
