# Generated by Django 3.2.8 on 2023-10-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eap_api", "0006_alter_eapuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="eapuser",
            name="auth_provider",
            field=models.CharField(default="legacy", max_length=200),
        ),
    ]
