# Generated by Django 3.2.8 on 2023-10-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eap_api", "0009_merge_20231013_0806"),
    ]

    operations = [
        migrations.AddField(
            model_name="assurancecase",
            name="color_profile",
            field=models.CharField(default="default", max_length=200),
        ),
    ]
