# Generated by Django 3.2.8 on 2021-11-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eap_api', '0009_auto_20211110_1654'),
        ('eap_api', '0009_auto_20211115_1615'),
    ]

    operations = [
    ]
