# Generated by Django 3.2.8 on 2022-04-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eap_api', '0011_auto_20220404_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyclaim',
            name='parent',
        ),
        migrations.AddField(
            model_name='propertyclaim',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_claims', to='eap_api.toplevelnormativegoal'),
        ),
        migrations.AddField(
            model_name='propertyclaim',
            name='property_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_claims', to='eap_api.propertyclaim'),
        ),
    ]
