# Generated by Django 3.2.8 on 2022-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eap_api', '0011_auto_20220405_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidentialclaim',
            name='argument',
        ),
        migrations.AddField(
            model_name='evidentialclaim',
            name='property_claim',
            field=models.ManyToManyField(related_name='evidential_claims', to='eap_api.PropertyClaim'),
        ),
        migrations.DeleteModel(
            name='Argument',
        ),
    ]
