# Generated by Django 3.2.8 on 2023-11-07 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eap_api", "0013_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
    ]
