# Generated by Django 3.2.8 on 2022-04-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eap_api", "0013_assurancecase_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyclaim",
            name="claim_type",
            field=models.CharField(
                choices=[("System claim", "System"), ("Project claim", "Project")],
                default="Project claim",
                max_length=32,
            ),
        ),
    ]
