# Generated by Django 3.2.8 on 2022-04-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eap_api", "0014_propertyclaim_claim_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assurancecase",
            name="editable",
        ),
        migrations.AddField(
            model_name="assurancecase",
            name="lock_uuid",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
