# Generated by Django 3.2.8 on 2024-07-03 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eap_api", "0016_auto_20240613_1028"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="assurance_case",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contexts",
                to="eap_api.assurancecase",
            ),
        ),
        migrations.AddField(
            model_name="context",
            name="in_sandbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evidence",
            name="assurance_case",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="eap_api.assurancecase",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="in_sandbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyclaim",
            name="assurance_case",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_claims",
                to="eap_api.assurancecase",
            ),
        ),
        migrations.AddField(
            model_name="propertyclaim",
            name="in_sandbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="strategy",
            name="assurance_case",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategies",
                to="eap_api.assurancecase",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="in_sandbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="toplevelnormativegoal",
            name="in_sandbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="context",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="propertyclaim",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="toplevelnormativegoal",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
