# Generated by Django 3.2.8 on 2024-07-08 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eap_api", "0019_merge_0017_auto_20240704_1601_0018_alter_context_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategies",
                to="eap_api.toplevelnormativegoal",
            ),
        ),
    ]
