# Generated by Django 3.2.8 on 2024-08-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eap_api", "0020_alter_strategy_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eapuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
