# Generated by Django 3.2.8 on 2024-09-13 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eap_api", "0022_assurancecase_review_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssuranceCaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default=None, upload_to="images/")),
                (
                    "assurance_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_image",
                        to="eap_api.assurancecase",
                    ),
                ),
            ],
        ),
    ]
