# Generated by Django 3.2.8 on 2025-02-26 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eap_api', '0031_casestudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_study', to=settings.AUTH_USER_MODEL),
        ),
    ]
