# Generated by Django 3.2.8 on 2025-02-26 14:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eap_api', '0036_alter_casestudy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedAssuranceCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assurance_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eap_api.assurancecase')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eap_api.casestudy')),
            ],
        ),
    ]
