# Generated by Django 3.2.8 on 2025-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eap_api', '0040_assurancecase_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurancecase',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
