# Generated by Django 3.2.8 on 2025-06-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eap_api', '0041_assurancecase_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedassurancecase',
            name='case_study',
        ),
    ]
