# Generated by Django 3.2.8 on 2025-06-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eap_api', '0042_remove_publishedassurancecase_case_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedassurancecase',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
