# Generated by Django 3.2.8 on 2025-07-10 13:00
# Step 3: Remove the old assurance_cases field pointing to AssuranceCase

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eap_api", "0045_populate_published_assurance_cases"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casestudy",
            name="assurance_cases",
        ),
    ]