version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "staging"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      major:
        update-types:
          - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "staging"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    groups:
      actions:
        patterns:
          - "*"
