// GENERATED by scripts/assistant/generate-ruleset.ts from ruleset v0.4 on 2026-09-15; do not edit
import type { RulesetData } from "./ruleset-types";

export const RULESET_DATA: RulesetData = {
	"version": "0.4",
	"date": "2026-09-15",
	"families": [
		{
			"prefix": "WORD",
			"name": "Wording",
			"defect": "the element's own text is malformed; fixed by rewriting it in place"
		},
		{
			"prefix": "PLAC",
			"name": "Misplacement",
			"defect": "the right content in the wrong element type; fixed by moving it"
		},
		{
			"prefix": "STEP",
			"name": "Decomposition",
			"defect": "the inference step from parent to children is unstated or unsound"
		},
		{
			"prefix": "EVID",
			"name": "Support",
			"defect": "evidence is missing or inadequate for the claim it carries"
		},
		{
			"prefix": "SCOP",
			"name": "Scope and inheritance",
			"defect": "what is in scope, and how context flows down the tree"
		},
		{
			"prefix": "TREE",
			"name": "Structure",
			"defect": "the graph itself: roots, cycles, orphans, undeveloped marks, away elements, labels"
		},
		{
			"prefix": "CONF",
			"name": "Confidence and defeat",
			"defect": "how strongly the case is established and what could undermine it"
		}
	],
	"rules": [
		{
			"id": "CONF01",
			"title": "The top goal states the confidence being claimed for it",
			"applies_to": [
				"GOAL"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "The case says how strongly the top claim is established: a qualitative level (low / medium / high), a range, or a stated residual uncertainty. Absolute certainty is not claimable and should not be implied by silence.",
			"ackable": false,
			"apply": {
				"look_for": "No qualitative level (low / medium / high), range, or stated residual uncertainty on the top goal's text, a justification line, or a context entry.",
				"not_when": "A level is stated, including a scoped one (\"medium, for the developed branches only; a planning case\"). A numeric confidence with no method is also CONF05's business — record both.",
				"wording": "Fix: the justification line stating the level and what it is scoped to."
			}
		},
		{
			"id": "CONF02",
			"title": "Lines of evidence under one claim should not share a failure mode",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "style",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Across a claim's sub-claims, prefer evidence with different failure modes (a benchmark, an expert study, a governance sign-off) over several artefacts that share one source of error. Applies to any claim node, not only the top goal.",
			"ackable": false,
			"question_text": "Do these lines of evidence fail together — a shared source, tool, team, dataset, or assumption?"
		},
		{
			"id": "CONF03",
			"title": "Defeated elements are reported, not propagated",
			"applies_to": [
				"GOAL"
			],
			"scope": "case",
			"severity": "warning",
			"mechanism": "structural",
			"mode": [
				"review"
			],
			"statement": "An element marked defeated (a counter-argument has been accepted against it; GSN §1:6, the dialectic extension, gives the notation) is flagged, and the checker names what sits above it. The checker does not mark ancestors unsupported; whether and how far defeat propagates is the reader's judgement.",
			"ackable": false
		},
		{
			"id": "CONF04",
			"title": "Defeaters have been sought",
			"applies_to": [
				"GOAL"
			],
			"scope": "case",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review"
			],
			"statement": "The case records what could undermine it and why it does not.",
			"ackable": false,
			"question_text": "What could undermine this case — a fact, a counter-argument, a shared failure — and where does the case record why it does not? If nothing is recorded, has the search been done?"
		},
		{
			"id": "CONF05",
			"title": "Confidence claims state their method",
			"applies_to": [
				"GOAL"
			],
			"scope": "case",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review"
			],
			"statement": "A numeric confidence score without a stated combination method is a red flag, not a strength; qualitative confidence (low / medium / high) is the safe default.",
			"ackable": false,
			"apply": {
				"look_for": "Anywhere in the case (descriptions, context, assumption, justification): a numeric confidence (\"95% confident\", \"confidence 0.8\", \"probability of the claim\") with no stated combination method.",
				"not_when": "Qualitative levels (low / medium / high). A measurement percentage (\"97.2% sensitivity\") is a property, not a confidence claim.",
				"wording": "Element: \"case\". Reason: quote the number. Fix: the method to state, or the qualitative level to use instead."
			}
		},
		{
			"id": "EVID01",
			"title": "A leaf claim has evidence",
			"applies_to": [
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "structural",
			"mode": [
				"review"
			],
			"statement": "A property claim with no sub-claims and no Evidence node is unsupported, unless it is marked undeveloped (TREE04).",
			"ackable": true,
			"fix": "Attach the Evidence node, add the sub-claims, or record honestly that support is still needed (assertionStatus NEEDS_SUPPORT)."
		},
		{
			"id": "EVID02",
			"title": "Evidence is a real, producible artefact",
			"applies_to": [
				"EVIDENCE"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Not a restatement of the claim, not a plan to produce something.",
			"ackable": false,
			"apply": {
				"look_for": "A description that restates the claim (\"The system is accurate\"), or is a plan (\"Testing will be carried out\"), or names a category (\"Testing\", \"Validation\") rather than an artefact. De-duplicate evidence by id first; the nested form repeats multi-linked evidence.",
				"not_when": "A named artefact that exists or can be produced: a report, a dataset, a measurement record, a signed review. Prose mentions of intended evidence in a claim's text or context are not evidence nodes and are not E findings.",
				"wording": "Reason: name what the description is instead of an artefact. Fix: the artefact to name, or the removal of the node with the claim marked as needing support."
			},
			"fix": "Name the artefact that exists, or remove the node and mark the claim as needing support."
		},
		{
			"id": "EVID03",
			"title": "Evidence is matched in kind to its claim",
			"applies_to": [
				"EVIDENCE"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Process evidence (training completed, audit held) does not establish an outcome claim (bias mitigated, system safe).",
			"ackable": false,
			"apply": {
				"look_for": "Process evidence (training completed, audit held, checklist signed) under an outcome claim (bias mitigated, accurate, safe); a measurement of X under a claim about Y. Name every parent claim the mismatch holds for.",
				"not_when": "The evidence's kind is what the claim asserts; or an intermediate claim the evidence does establish sits between them.",
				"wording": "Reason: name the artefact, what it shows, and what the claim asserts. Fix: the intermediate claim to insert, or the outcome evidence to seek, named."
			},
			"fix": "Either insert an intermediate claim the evidence does establish (\"all radiologists completed the module\"), or find outcome evidence."
		},
		{
			"id": "EVID04",
			"title": "Evidence is specific and located",
			"applies_to": [
				"EVIDENCE"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Name the artefact and, where it is a document, the section or table.",
			"ackable": false,
			"apply": {
				"look_for": "A whole document with no section, table or record type; \"the validation report\".",
				"not_when": "A section, table, figure, record type, or query is named.",
				"wording": "Fix: the locator to add."
			}
		},
		{
			"id": "EVID05",
			"title": "Evidence is verifiable and traceable",
			"applies_to": [
				"EVIDENCE"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Someone outside the team could locate and check it.",
			"ackable": false,
			"apply": {
				"look_for": "No way for someone outside the team to locate the artefact: no url, no document reference, no repository or record identifier, and the description gives none.",
				"not_when": "A url, a document reference, a record identifier, or a described location is given.",
				"wording": "Fix: the reference or identifier to add."
			}
		},
		{
			"id": "EVID06",
			"title": "Evidence discriminates",
			"applies_to": [
				"EVIDENCE"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review"
			],
			"statement": "Evidence that would look the same whether the claim were true or false is not support.",
			"ackable": false,
			"apply": {
				"look_for": "An artefact that would look the same whether the claim were true or false: a completion certificate; a log that only records that a step ran.",
				"not_when": "The artefact's content varies with the truth of the claim.",
				"wording": "Reason: say why the artefact would look the same either way. Fix: the discriminating evidence to seek."
			}
		},
		{
			"id": "EVID07",
			"title": "An Evidence node records its scope, its uncertainty, and its assumptions",
			"applies_to": [
				"EVIDENCE"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Beyond naming the artefact, say what it applies to, how trustworthy its source and measurement are, and what it assumes.",
			"ackable": false,
			"apply": {
				"look_for": "The description names the artefact and nothing else. Partial coverage is a finding whose reason names which of the three is missing.",
				"not_when": "Scope of applicability, a credibility or accuracy statement, and the assumptions are given in the description or in attached context or assumption fields.",
				"wording": "Fix: the sentence to append naming the missing item(s)."
			}
		},
		{
			"id": "PLAC01",
			"title": "A claim does not state its own evidence",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "\"Testing shows…\", \"Experts judge…\", \"The audit found…\" describe evidence. The claim is the property that evidence is meant to show.",
			"ackable": false,
			"apply": {
				"look_for": "\"Testing shows\", \"Experts judge\", \"The audit found\", \"Validation demonstrates\" as the claim's verb phrase.",
				"not_when": "Claim and evidence describe the same fact because the step is evidence incorporation (a property claim whose only child is the evidence node that establishes it). Mention it in the report's notes; do not record it as a finding.",
				"wording": "Reason: quote the evidential phrase. Fix: the property kept as the claim, and the evidential phrase named as the Evidence node to add."
			},
			"fix": "Move the evidential phrase into an Evidence node; keep the property."
		},
		{
			"id": "PLAC02",
			"title": "A strategy carries no claims",
			"applies_to": [
				"STRATEGY"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review"
			],
			"statement": "A strategy that asserts something (\"… which is complete\", \"… using validated tools\") is hiding a claim that will never be supported.",
			"ackable": false,
			"apply": {
				"look_for": "An assertion in passing: \"… which is complete\", \"… using validated tools\", \"… each of which is mitigated\".",
				"not_when": "The text only names the approach; assertions live in the children or in a justification. A statement about how future evidence will enter the case is not a claim about the system.",
				"wording": "Reason: quote the assertion. Fix: the Property Claim or Assumption to lift it into."
			},
			"fix": "Lift the assertion into a Property Claim or an Assumption."
		},
		{
			"id": "PLAC03",
			"title": "Context is not evidence",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM",
				"STRATEGY",
				"CONTEXT",
				"ASSUMPTION",
				"JUSTIFICATION"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "A context entry states scope, definitions or the system boundary; it does not carry information offered in support of a claim's validity. That is evidence and belongs in an Evidence node.",
			"ackable": false,
			"apply": {
				"look_for": "Per context entry: the entry offers information in support of the claim's validity — a result, a measurement, a study outcome (\"Validation study, 97.2% sensitivity\").",
				"not_when": "The entry fixes scope, meaning or boundary: a definition, an operating envelope, a system boundary, a document that defines the set or the terms.",
				"wording": "Field: the context locator. Fix: the Evidence node to move it to."
			},
			"fix": "Move it to an Evidence node."
		},
		{
			"id": "PLAC04",
			"title": "An unsupported proposition is an Assumption, not Context",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM",
				"STRATEGY",
				"CONTEXT",
				"ASSUMPTION",
				"JUSTIFICATION"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review"
			],
			"statement": "A context entry that is a proposition taken as true, rather than a reference to an artefact or a definition, is an assumption and should be recorded as one.",
			"ackable": false,
			"apply": {
				"look_for": "Per context entry: a proposition taken as true (\"System X has no common-mode failures\", \"the recordings are a faithful record\") rather than a definition or a reference.",
				"not_when": "The entry is a definition, a scope statement, or a reference to an artefact that fixes meaning; or a set-determination rationale that STEP08 permits as context.",
				"wording": "Field: the context locator. Fix: the assumption line to move it to."
			},
			"fix": "Move the entry to the element's assumption field."
		},
		{
			"id": "PLAC05",
			"title": "An Assumption that is doing argumentative work needs support",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM",
				"STRATEGY",
				"CONTEXT",
				"ASSUMPTION",
				"JUSTIFICATION"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review"
			],
			"statement": "If the case would fall without it and it could be evidenced, it is a claim wearing an Assumption label.",
			"ackable": false,
			"apply": {
				"look_for": "Per assumption line, and any element with assertionStatus ASSUMED or AXIOMATIC (the precheck lists them): the case would fall without it, and it could be evidenced (a provenance record exists or could).",
				"not_when": "It is genuinely unevidenceable in this case. Where the author has recorded why it is left as an assumption, the finding stands and the reason says so.",
				"wording": "Field: the assumption locator. Fix: the claim to promote it to and the evidence it would carry, or the note that it stays as an accepted gap."
			},
			"fix": "Promote it to a Property Claim with evidence, or record why it is left unsupported."
		},
		{
			"id": "PLAC06",
			"title": "Justification explains, it does not assert",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM",
				"STRATEGY",
				"CONTEXT",
				"ASSUMPTION",
				"JUSTIFICATION"
			],
			"scope": "element",
			"severity": "style",
			"mechanism": "judgement",
			"mode": [
				"review"
			],
			"statement": "A justification gives the rationale for an element's inclusion or phrasing; it does not add a claim of its own.",
			"ackable": false,
			"apply": {
				"look_for": "Per justification line: the line adds a claim of its own (\"… and the HAZOP is complete\") rather than giving the reason for the element's inclusion or phrasing.",
				"not_when": "The line pins a qualifier (what \"adequately\" means), explains a sequencing choice, or gives the rationale for a slot's inclusion — explanation, not assertion.",
				"wording": "Field: the justification locator. Fix: the Property Claim or Assumption to move the assertion to."
			}
		},
		{
			"id": "SCOP01",
			"title": "The top goal's use scope is determinate",
			"applies_to": [
				"GOAL"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "The deployment or use scope in which the property is claimed is recorded in a Context element attached to the top goal. Exceptionally it may sit in the goal text, where the scope is inseparable from the claim itself. Scope written into the goal sentence is not the norm: it cannot be inherited by the argument beneath (SCOP02), it lengthens the claim towards a second proposition (WORD01), and GSN gives scope its own element type.",
			"ackable": false,
			"apply": {
				"look_for": "The top goal's context list is empty (the SCOP01 precheck says so), or no entry names the use or deployment scope — what the system is used for, by whom, in what setting. A definitions entry or an operating-envelope entry is not a use scope on its own. Scope folded into the goal sentence rather than a context entry.",
				"not_when": "A context entry names the use scope; or the scope is in the goal text and the claim would be a different claim without it (say which case applies in the reason).",
				"wording": "Fix: the exact context line to add to the top goal."
			},
			"fix": "Add a Context element naming the use scope; only fold it into the goal text when the claim would be a different claim without it."
		},
		{
			"id": "SCOP02",
			"title": "Context is inherited; do not restate it below",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM",
				"STRATEGY",
				"CONTEXT",
				"ASSUMPTION",
				"JUSTIFICATION"
			],
			"scope": "element",
			"severity": "style",
			"mechanism": "structural",
			"mode": [
				"authoring"
			],
			"statement": "Context applies to the entire supporting argument, so it is not restated on descendants. Carve-out — narrowing is not restating: a child context that reduces an inherited constraint is a distinct and legitimate move governed by SCOP04, and must not be reported as a restatement. Compare the constraint, not the string.",
			"ackable": false
		},
		{
			"id": "SCOP03",
			"title": "Justification is local; restate or re-link where needed",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM",
				"STRATEGY",
				"CONTEXT",
				"ASSUMPTION",
				"JUSTIFICATION"
			],
			"scope": "element",
			"severity": "style",
			"mechanism": "judgement",
			"mode": [
				"authoring"
			],
			"statement": "Unlike context, a justification applies only to the element it is attached to; a sub-claim that needs the same rationale must restate it or re-link it.",
			"ackable": false
		},
		{
			"id": "SCOP04",
			"title": "A child context may narrow an inherited one, but must declare it and discharge it",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM",
				"STRATEGY",
				"CONTEXT",
				"ASSUMPTION",
				"JUSTIFICATION"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Reducing the scope of an inherited context lower in the argument is legitimate and common. It carries two obligations, not one: the reduction is stated explicitly at the point it occurs, and the remainder is discharged — covered by a sibling claim, or the parent re-scoped to what is actually supported. Declaring a reduction makes the shortfall legible; it does not make the parent supported.",
			"ackable": false,
			"apply": {
				"look_for": "Per context entry, against every ancestor's entry on the same dimension (envelope, population, phase, term): this entry reduces the scope, and either the reduction is not stated as such, or the remainder is not covered by a sibling claim or a re-scoped parent. The narrowing prechecks are the shortlist; read every entry against its ancestors'.",
				"not_when": "Equal scope (SCOP02's case); a new dimension the ancestor never mentions (addition, expected); a declared reduction whose remainder is discharged.",
				"wording": "Reason: quote the entry and name the ancestor entry it narrows. Fix: the re-scoped parent line, or the sibling claim to add."
			},
			"fix": "Add the sibling that covers the remainder, or pull the parent's scope in to match what the children establish."
		},
		{
			"id": "SCOP05",
			"title": "A child context does not relax an inherited constraint",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM",
				"STRATEGY",
				"CONTEXT",
				"ASSUMPTION",
				"JUSTIFICATION"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "For any dimension the parent constrains, a child may not widen it. A child may freely constrain a dimension the parent never mentioned — that is addition, not relaxation, and is expected. The test is per-dimension: context is a conjunction of constraints (operating envelope, system boundary, term definitions, lifecycle phase), not a single set, so the relation to check is B ⊆ A on each dimension the parent constrains, with equality the normal case — not B ⊂ A, which would wrongly require every child to narrow and would contradict SCOP02.",
			"ackable": false,
			"apply": {
				"look_for": "Per context entry: on a dimension an ancestor constrains, this entry widens it (\"urban roads\" → \"urban and motorway\").",
				"not_when": "A new dimension; or equal or narrower scope.",
				"wording": "Reason: quote both entries and name the dimension. Fix: the re-scoped parent line, or the narrowed child line."
			},
			"fix": "Re-scope the parent to the wider context if that is what is meant, or narrow the child to what the parent claims."
		},
		{
			"id": "STEP01",
			"title": "Sibling claims are jointly sufficient for their parent",
			"applies_to": [
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "If all the sub-claims under a strategy were true, the parent would be established. A gap is a missing sub-claim or an unstated Assumption.",
			"ackable": false,
			"fix": "Add the missing claim, or an Assumption node that says what is being taken for granted.",
			"question_text": "If every sibling claim under this strategy were true, would the parent claim be established — and what is being taken for granted in saying so? Name any missing sub-claim or unstated assumption."
		},
		{
			"id": "STEP02",
			"title": "Sibling claims are not redundant",
			"applies_to": [
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Two sub-claims that establish the same thing add cost without support.",
			"ackable": false,
			"apply": {
				"look_for": "Applied once per sibling set (the property claims under one strategy or claim): two siblings that establish the same proposition, or one entailed by another (if A holds, B cannot fail).",
				"not_when": "Siblings overlap in wording but constrain different dimensions (data completeness and data consistency).",
				"wording": "Element: the first sibling; name the other in the reason. Fix: which to merge or drop."
			}
		},
		{
			"id": "STEP03",
			"title": "A strategy names the decomposition",
			"applies_to": [
				"STRATEGY"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Applies when a strategy node is present; an absent strategy is STEP07. \"Argument over hazards\", \"Argument over lifecycle stages\", \"Argument by appeal to independent validation\" — the reader must see the rule by which sub-claims were chosen.",
			"ackable": false,
			"apply": {
				"look_for": "Vacuous text (\"We decompose the goal\", \"See below\", \"Argument\"), or text from which a reader cannot state the rule by which the children were chosen.",
				"not_when": "\"Argument over <a named set or attribute list>\", \"Argument by appeal to <method>\", or any phrasing from which the decomposition rule can be stated.",
				"wording": "Reason: quote the strategy text. Fix: the \"Argument over …\" line to replace it with."
			}
		},
		{
			"id": "STEP04",
			"title": "A strategy's basis is stated",
			"applies_to": [
				"STRATEGY"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Why this decomposition is adequate (completeness of the hazard list, independence of the attributes) is stated in a Justification, and anything taken for granted is an Assumption.",
			"ackable": false,
			"apply": {
				"look_for": "No justification on the strategy (or its parent claim) says why this decomposition is adequate, and nothing taken for granted is recorded as an assumption.",
				"not_when": "A justification or assumption states the basis, even briefly, including one on an ancestor that names this strategy; or a supporting claim argues it (STEP09).",
				"wording": "Reason: say where a basis was looked for. Fix: the justification line to add."
			}
		},
		{
			"id": "STEP05",
			"title": "Removability",
			"applies_to": [
				"STRATEGY"
			],
			"scope": "element",
			"severity": "style",
			"mechanism": "judgement",
			"mode": [
				"authoring"
			],
			"statement": "Removing every strategy node should leave the claims still readable as an argument.",
			"ackable": false,
			"question_text": "If every strategy node were removed, would the claims still read as an argument? Check the flow from parent to children without the strategy text."
		},
		{
			"id": "STEP06",
			"title": "Name the inference type",
			"applies_to": [
				"STRATEGY"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"authoring"
			],
			"statement": "When drafting a step, say which of the CAE building blocks it is: decomposition, substitution, concretion, calculation, or evidence incorporation. Concretion (replacing a vague claim with a precise one) must be flagged explicitly because it can break the chain of reasoning.",
			"ackable": false,
			"question_text": "Which kind of step is this — decomposition, substitution, concretion, calculation, or evidence incorporation? If it is a concretion (a vague claim replaced by a precise one), say so explicitly: it can break the chain of reasoning."
		},
		{
			"id": "STEP07",
			"title": "An implicit strategy is acceptable only when the decomposition is obvious",
			"applies_to": [
				"STRATEGY"
			],
			"scope": "element",
			"severity": "style",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Where a claim has sub-claims and no strategy node, the reader should be able to state the decomposition rule unprompted; if not, add the node.",
			"ackable": false,
			"apply": {
				"look_for": "Applies to a claim with claim-children and no Strategy child (the STEP07 precheck lists them): a reader could not state the decomposition rule unprompted.",
				"not_when": "The decomposition is obvious from the children (a claim split into its two named halves).",
				"wording": "Element: the claim. Fix: the strategy line to add beneath it."
			}
		},
		{
			"id": "STEP08",
			"title": "A strategy arguing over a set names how the set was determined",
			"applies_to": [
				"STRATEGY"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Where a strategy argues over the members of a set — hazards, lifecycle stages, functions, operating modes, requirements — the case must record how that set was arrived at. The determining artefact may be attached to the strategy as a Context, an Assumption, or a Justification, or supplied as a supporting claim where it needs an argument of its own (STEP09); all four are permitted homes and the rule is satisfied by any of them. \"Argument over hazards\" with none of them is an argument over an unbounded set.",
			"ackable": false,
			"apply": {
				"look_for": "The strategy argues over members of a set (hazards, conditions, constituents, stages, parameters) and none of a context entry, an assumption, a justification, or a supporting claim — on the strategy or inherited from an ancestor — says how that set was arrived at.",
				"not_when": "Any of the four homes names the method or artefact (\"as identified by the HAZOP of 2026-03\", \"Table 1 of the planning document\", \"the architecture description's constituent inventory\"); or the strategy does not argue over a set (by attribute, by appeal to a method). When you record an STEP08 finding the checker will usually also have raised the STEP01/STEP10 question on the same strategy; both stand.",
				"wording": "Reason: quote the strategy text and name the missing home. Fix: the exact context line to add, or the claim to promote."
			},
			"fix": "Attach the method and its output (the hazard log, the standard's lifecycle-stage list, the requirements baseline) in whichever of the four homes fits its scope — an Assumption if the set is taken as given without support, a supporting claim if its adequacy is itself arguable."
		},
		{
			"id": "STEP09",
			"title": "The adequacy of the set is a supported claim, not merely a stated one",
			"applies_to": [
				"STRATEGY"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "STEP08 requires the set-determination method to be named; STEP09 requires that, where the adequacy of that set is arguable, it is carried as a claim with support beneath it rather than asserted in passing. Naming a HAZOP does not establish that the HAZOP was adequate.",
			"ackable": false,
			"apply": {
				"look_for": "The set's adequacy is arguable and is only asserted (a justification or context saying \"the HAZOP covers all hazards\", or \"adequacy asserted, not argued; open\") with no claim beneath carrying it.",
				"not_when": "The adequacy is carried as a supporting claim with evidence, or an away goal. Where the author has recorded it as open, the finding stands and the reason says so.",
				"wording": "Fix: the claim to promote (or the away goal to link) and the evidence it would carry."
			},
			"fix": "Promote the adequacy statement to a supporting claim (or an away goal into a module) and give it evidence."
		},
		{
			"id": "STEP10",
			"title": "The claimed property distributes over the set",
			"applies_to": [
				"STRATEGY"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Completeness of the set is not sufficiency. Even given every hazard, arguing over hazards works only if mitigating each member establishes the parent claim. This is the other half of STEP01 and carries the question marker for the same reason: it needs a reader.",
			"ackable": false,
			"fix": "State the distribution assumption as an Assumption on the strategy, or add the missing sub-claim.",
			"question_text": "If every member of this set were established, would the parent claim hold — and what is being assumed in saying so?"
		},
		{
			"id": "STEP11",
			"title": "No leaps of faith",
			"applies_to": [
				"GOAL"
			],
			"scope": "case",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review"
			],
			"statement": "Every claim terminates in evidence or a well-formed sub-claim; no claim is supported by evidence far below it in abstraction without intermediate claims.",
			"ackable": false,
			"apply": {
				"look_for": "Applied last, after the whole tree: a claim supported directly by evidence far below it in abstraction with no intermediate claim (a top-level \"the system is safe\" over a unit-test log; an outcome claim on one raw measurement with no aggregation claim between); or children that together sit several levels below their parent with nothing between.",
				"not_when": "An evidence-incorporation step where claim and artefact describe the same fact. In a case with no evidence the rule cannot fire — say so in the report's notes.",
				"wording": "Element: \"case\". Reason: name the claim, the evidence and the levels skipped. Fix: the intermediate claim(s) to insert."
			}
		},
		{
			"id": "TREE01",
			"title": "One root per case (or per module)",
			"applies_to": [
				"GOAL"
			],
			"scope": "case",
			"severity": "warning",
			"mechanism": "structural",
			"mode": [
				"review"
			],
			"statement": "A case has one top goal. Several unconnected roots are several cases; a second root is usually an orphaned branch.",
			"ackable": false
		},
		{
			"id": "TREE02",
			"title": "Acyclic",
			"applies_to": [
				"GOAL"
			],
			"scope": "case",
			"severity": "error",
			"mechanism": "structural",
			"mode": [
				"review"
			],
			"statement": "No element supports itself, directly or indirectly.",
			"ackable": false
		},
		{
			"id": "TREE03",
			"title": "No orphan or dangling elements",
			"applies_to": [
				"GOAL"
			],
			"scope": "case",
			"severity": "error",
			"mechanism": "structural",
			"mode": [
				"review"
			],
			"statement": "Every element has a parent (except the root); every strategy has children; every Evidence node supports something.",
			"ackable": true
		},
		{
			"id": "TREE04",
			"title": "Undeveloped branches are marked, not left looking complete",
			"applies_to": [
				"GOAL"
			],
			"scope": "case",
			"severity": "warning",
			"mechanism": "structural",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "A branch the author has deliberately left to be developed is visibly marked as such.",
			"ackable": false
		},
		{
			"id": "TREE05",
			"title": "Away elements match their originals exactly",
			"applies_to": [
				"GOAL"
			],
			"scope": "case",
			"severity": "error",
			"mechanism": "structural",
			"mode": [
				"review"
			],
			"statement": "In a case split across modules, an away element is a stand-in that refers to a goal, solution or context defined in another module. Its text must be identical to the original, so the reader is never checking a paraphrase.",
			"ackable": false
		},
		{
			"id": "TREE06",
			"title": "Display labels index from 1",
			"applies_to": [
				"GOAL"
			],
			"scope": "case",
			"severity": "style",
			"mechanism": "structural",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "The top goal is G1, its strategy S1, the first property claim P1, the first evidence node E1, and so on; no element is labelled 0. Children extend the parent's label (P1.1, P1.1.2). Prefixes follow GSN: G goal, P property claim (TEA's name for a sub-goal), S strategy, E evidence, C context, A assumption, J justification (context elements start with C, not X). Element labels are unpadded (C1, C2) and rule IDs in this catalogue are two-digit (WORD01, WORD02), so the two namespaces do not collide. Labels are display names only and are never used to bind evidence (records bind to the element's stable id).",
			"ackable": false,
			"fix": "Renumber from 1."
		},
		{
			"id": "WORD01",
			"title": "One claim per node",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "A claim states exactly one proposition. Conjunctions (\"X and Y\") are two claims and belong in two nodes beneath a strategy.",
			"ackable": false,
			"apply": {
				"look_for": "An \"and\", \"while also\" or comma-list joining two properties; a sentence that would be two claims if split at the conjunction.\nA conjunction is not the only carrier. Two further forms, both missed by an earlier version of this rule on a real case:\n(a) A trailing participial clause can hide a second condition — \"... is handed into the FIR\", \"... running at the published rate\". Ask whether the clause states a further thing that must be true, or only describes the thing already claimed. If it must be true, it is a second claim.\n(b) An \"or\" between two measures is two candidate claims, not one — \"at most n aircraft (or a complexity score <= c)\". An unresolved alternative means the acceptance criterion has not been chosen, which is worse than a compound claim rather than better.",
				"not_when": "The conjunction joins a property to its criterion or scope (\"accurate to within 0.5 NM at a 1-minute horizon\"); a list inside a definition (\"complete = a filed flight plan with at least two route fixes, and sector entry and exit levels\") is one proposition defining a term. Where the strategy beneath immediately splits the pair and the author has recorded a waiver, record the finding anyway — the report shows it and the reader decides.",
				"wording": "Reason: name the two propositions. Fix: give the two split claims and the strategy line."
			},
			"fix": "Split at each conjunction; add a strategy naming the decomposition."
		},
		{
			"id": "WORD02",
			"title": "A claim is a proposition",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "The text must be something that is true or false of the system or project: not an instruction, an aspiration, a process description, or a belief report.",
			"ackable": false,
			"apply": {
				"look_for": "Imperatives (\"Improve\", \"Ensure\"), aspirations (\"aims to\"), process descriptions (\"is documented and governed\"), belief reports (\"We believe\").",
				"not_when": "A declarative sentence about the system or project that could be false.",
				"wording": "Reason: name the form the text takes (instruction, process, belief report). Fix: the rewrite as \"The <system/project> <has/does> <property>\"."
			},
			"fix": "Rewrite as \"The <system/project> <has/does> <property>\"."
		},
		{
			"id": "WORD03",
			"title": "The subject is the system or its governing project",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "error",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "The grammatical subject of the claim is the system being assured, a component of it, or the project that develops and governs it. Users, regulators and third parties are not valid subjects.",
			"ackable": false,
			"apply": {
				"look_for": "The grammatical subject is a user, operator, regulator, patient, a stakeholder group, real-world traffic, the weather — anything the project cannot discharge with its own evidence.",
				"not_when": "The subject is the system, a named component or constituent, the system's ingested state or modelled view of the world, or the project. A human may appear as the criterion (\"legible to a domain expert\").",
				"wording": "Reason: name the subject as written. Fix: the recast with the system or project as actor, the human behaviour moved into the criterion."
			},
			"fix": "Recast so the system or project is the actor; the human behaviour becomes the criterion (\"… legible to a domain expert\")."
		},
		{
			"id": "WORD04",
			"title": "No vague predicate without a definition in scope",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "Words such as \"good\", \"robust\", \"appropriate\", \"effective\", \"timely\", \"normal\", \"seamless\" and \"useful\" need a Context or Justification that says what they mean here, or a rewrite that names the measurable property.",
			"ackable": false,
			"apply": {
				"look_for": "GSN's list (abnormal, appropriate, approximate, effective, early, easy, envelope, flexible, friendly, generally, late, normal, often, timely) and words of the same kind — good, robust, seamless, useful, trustworthy, faithful, accurate, sufficient, similar, calibrated, buffer — with nothing in scope defining them. Also overstatement (all, any, each, every, typical) with no bounding set.\nInclude the assurance-process participles: validated, verified, approved, qualified, certified, accepted (added after a \"validated\" operating domain went unflagged on a real case). These read as though they name a completed procedure and so escape the vague-word list, but \"validated\" without a stated validation — against what, by whom, to what criterion — is exactly as undefined as \"appropriate\", and more misleading because it implies a record exists.",
				"not_when": "The word is defined in a context entry or justification on the element or any ancestor (context is inherited), or the sub-claims beneath operationalise it. Check the ancestors before writing.",
				"wording": "Reason: name the word and say where you looked (\"no context entry on P7 or its ancestors defines it\"). Fix: the rewrite naming the measurable property, or the exact context line to add and on which element."
			},
			"fix": "Name the measurable property, or attach a Context node defining the term."
		},
		{
			"id": "WORD05",
			"title": "An acceptability qualifier must be pinned somewhere in scope",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "\"Sufficiently\", \"acceptably\", \"as far as reasonably practicable\" are allowed and often necessary. When used, the criterion (acceptable to whom, judged how, for what use) must be pinned by a Context or Justification node or by the sub-claims that follow.",
			"ackable": false,
			"apply": {
				"look_for": "\"sufficiently\", \"acceptably\", \"adequately\", \"as far as reasonably practicable\", \"within acceptable bounds\" with no criterion (to whom, judged how, for what use) anywhere in scope or in the sub-claims.",
				"not_when": "A justification or context on the element or an ancestor pins the criterion, or the sub-claims' thresholds do. A criterion that is itself a placeholder (\"bounds to be derived\") is a finding — say in the reason that it is recorded as open by the author.",
				"wording": "Reason: name the qualifier and where the criterion should have been. Fix: the justification line to add, or the threshold to replace the qualifier with."
			},
			"fix": "Add the Justification, or replace the qualifier with the threshold."
		},
		{
			"id": "WORD06",
			"title": "A claim is specific enough that identifiable evidence could support it",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "A reader should be able to say what artefact would show this claim true.",
			"ackable": false,
			"apply": {
				"look_for": "\"The system is trustworthy\", \"is safe\", \"is fair\" — a claim with no property a reader could point an artefact at.",
				"not_when": "The claim names a measurable property, or the leaf names an identifiable evidence slot.",
				"wording": "Reason: say what artefact a reader would fail to point at. Fix: the rewrite that names it."
			},
			"fix": "Ask \"what would I point at?\" and rewrite to name that."
		},
		{
			"id": "WORD07",
			"title": "A strategy is phrased from the argument's perspective, not the system's",
			"applies_to": [
				"STRATEGY"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"authoring"
			],
			"statement": "A strategy is written as an argument step (\"Argument by appeal to …\", \"Argument over …\"), not as a description of what the system does or what the team did.",
			"ackable": false
		},
		{
			"id": "WORD08",
			"title": "Element text is case text, not working notes",
			"applies_to": [
				"GOAL",
				"PROPERTY_CLAIM",
				"STRATEGY",
				"CONTEXT",
				"ASSUMPTION",
				"JUSTIFICATION",
				"EVIDENCE"
			],
			"scope": "element",
			"severity": "warning",
			"mechanism": "judgement",
			"mode": [
				"review",
				"authoring"
			],
			"statement": "An element's text is the claim, scope, rationale or evidence description itself. It does not carry authoring provenance, working notes, rule ids, or statements about how the case was constructed.",
			"ackable": false,
			"apply": {
				"look_for": "Anything in an element's text that addresses the reader of the project rather than the reader of the argument. Four forms, all found on one real case:\n(a) Authoring provenance — people's names, dates, \"agreed with\", \"the lead decided\", open-question references, evidence-slot placeholders, grammar notes to a co-author.\n(b) Rule ids from this or any other checker (\"rule SCOP01\"), which bleed in when an author edits against a lint report.\n(c) Meta-argumentation — text about how the case is built rather than what it claims: \"every leaf threshold is derived from this criterion\", \"the bounds shown are provisional until derived\", \"each step is a concretion\".\n(d) Platform or tooling behaviour described as though it were argument content.",
				"not_when": "A date, name or version that is part of the claim's own scope (\"the model released on 2026-03-01\", \"the CAA's published minima\") is case text and stays. A Context entry naming a governing document is scope, not provenance. The test is whether a reader assessing the argument needs it in order to judge the claim.",
				"wording": "Reason: quote the offending span and name which form it is. Fix: the element text with the span removed, and where the removed content belongs — the case description, the companion case, an assertionStatus, or nowhere."
			},
			"fix": "Delete the span from the element. If it records real information, rehome it — status to assertionStatus, derivation method to the companion case, provenance to the case description or the work-tracking record."
		}
	]
};
