// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  teaSidebar: [
    "docs/intro",
    "docs/about",
    {
      type: "category",
      label: "TEA Skills and Capabilities Resources",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "docs/skills-resources/index",
        },
        {
          type: "category",
          label: "TEA Trainee",
          collapsible: true,
          collapsed: true,
          items: [
            "docs/skills-resources/tea-trainee/index",
            "docs/skills-resources/tea-trainee/first-sip",
          ],
        },
        {
          type: "category",
          label: "TEA Specialist",
          collapsible: true,
          collapsed: true,
          items: ["docs/skills-resources/tea-specialist/index"],
        },
        {
          type: "category",
          label: "TEA Expert",
          collapsible: true,
          collapsed: true,
          items: ["docs/skills-resources/tea-expert/index"],
        },
        {
          type: "category",
          label: "Hands-On Resources",
          collapsible: true,
          collapsed: true,
          items: ["docs/skills-resources/hands-on/index"],
        },
        {
          type: "category",
          label: "Standalone Resources",
          collapsible: true,
          collapsed: true,
          items: [
            "docs/skills-resources/standalone/index",
            "docs/skills-resources/standalone/standards",
            "docs/skills-resources/standalone/assurance-ecosystem",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Technical Documentation",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "docs/technical-guide",
        },
      ],
    },
    {
      type: "category",
      label: "Community Resources",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "docs/community",
        },
      ],
    },
  ],
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
