version: "3.8"

services:
  app:
    image: tea-fronted-production:latest
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
      args:
        GITHUB_APP_CLIENT_ID: ${GITHUB_APP_CLIENT_ID}
        GITHUB_APP_CLIENT_SECRET: ${GITHUB_APP_CLIENT_SECRET}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        API_URL: ${API_URL}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
    environment:
      GITHUB_APP_CLIENT_ID: ${GITHUB_APP_CLIENT_ID}
      GITHUB_APP_CLIENT_SECRET: ${GITHUB_APP_CLIENT_SECRET}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      API_URL: ${API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
