name: Backend CI/CD

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "tea_backend/**"
      - ".github/workflows/backend-ci-cd.yaml"
  push:
    branches:
      - main
      - staging
    paths:
      - "tea_backend/**"
      - ".github/workflows/backend-ci-cd.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/tea-backend

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-3.12-${{ hashFiles('tea_backend/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-3.12-
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: uv sync --frozen --python 3.12
        working-directory: tea_backend

      - name: Run type checking
        run: uv run mypy .
        working-directory: tea_backend

      - name: Run linting
        run: uv run ruff check .
        working-directory: tea_backend

      - name: Run formatting check
        run: uv run ruff format --check .
        working-directory: tea_backend

      - name: Run unit tests with coverage
        run: |
          uv run coverage run manage.py test -v 2
          uv run coverage report --show-missing
          uv run coverage xml
          # Extract coverage percentage for badge
          COVERAGE=$(uv run coverage report --format=total)
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          # Add coverage to workflow summary
          echo "### Backend Test Coverage :test_tube:" >> $GITHUB_STEP_SUMMARY
          echo "**Coverage:** ${COVERAGE}%" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          uv run coverage report >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        working-directory: tea_backend

      - name: Update coverage badge
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ secrets.COVERAGE_GIST_ID }}
          filename: backend-coverage.json
          label: backend coverage
          message: ${{ env.COVERAGE }}%
          color: ${{ env.COVERAGE >= 80 && 'brightgreen' || env.COVERAGE >= 60 && 'yellow' || 'red' }}

  integration-tests:
    name: Integration Tests
    needs: quality-checks
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tea_test
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --frozen
        working-directory: tea_backend

      - name: Run integration tests
        run: uv run python manage.py test -v 2 --tag=integration
        working-directory: tea_backend
        env:
          DBHOST: localhost
          DBPORT: 5432
          DBNAME: tea_test
          DBUSER: postgres
          DBPASSWORD: postgres

  build:
    name: Build and Push Docker Image
    needs: [quality-checks, integration-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Branch name
            type=ref,event=branch
            # PR number
            type=ref,event=pr
            # SHA (short)
            type=sha,prefix={{branch}}-
            # For main branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            # For staging branch
            type=raw,value=staging,enable=${{ github.ref == 'refs/heads/staging' }}
            type=raw,value=staging-{{date 'YYYY-MM-DD'}}-{{sha}},enable=${{ github.ref == 'refs/heads/staging' }}
            # Semantic versions (for releases)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./tea_backend
          file: ./tea_backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            BUILDKIT_INLINE_CACHE=1
