name: Frontend CI/CD

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "tea_frontend/**"
      - ".github/workflows/frontend-ci-cd.yaml"
  push:
    branches:
      - main
      - staging
    paths:
      - "tea_frontend/**"
      - ".github/workflows/frontend-ci-cd.yaml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/tea-frontend

defaults:
  run:
    working-directory: ./tea_frontend

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable pnpm

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('tea_frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type checking
        run: npx tsc --noEmit

      - name: Check formatting and linting
        run: pnpm exec ultracite lint

      - name: Run tests with coverage
        run: |
          pnpm test:coverage
          # Extract coverage percentage from lcov
          COVERAGE=$(lcov --summary coverage/lcov.info 2>&1 | grep -oP 'lines\.*: \K[0-9.]+' | head -1)
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          # Add coverage to workflow summary
          echo "### Frontend Test Coverage :test_tube:" >> $GITHUB_STEP_SUMMARY
          echo "**Coverage:** ${COVERAGE}%" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        env:
          NODE_ENV: test

      - name: Check coverage thresholds
        run: pnpm test:coverage:check

      - name: Update coverage badge
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ secrets.COVERAGE_GIST_ID }}
          filename: frontend-coverage.json
          label: frontend coverage
          message: ${{ env.COVERAGE }}%
          color: ${{ env.COVERAGE >= 80 && 'brightgreen' || env.COVERAGE >= 60 && 'yellow' || 'red' }}

      - name: Build application
        run: pnpm build
        env:
          GITHUB_APP_CLIENT_ID: ${{ secrets.GH_APP_CLIENT_ID_STAGING }}
          GITHUB_APP_CLIENT_SECRET: ${{ secrets.GH_APP_CLIENT_SECRET_STAGING }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET_STAGING }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL_STAGING }}

  build:
    name: Build and Push Docker Image
    needs: quality-checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Branch name
            type=ref,event=branch
            # PR number
            type=ref,event=pr
            # SHA (short)
            type=sha,prefix={{branch}}-
            # For main branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            # For staging branch
            type=raw,value=staging,enable=${{ github.ref == 'refs/heads/staging' }}
            type=raw,value=staging-{{date 'YYYY-MM-DD'}}-{{sha}},enable=${{ github.ref == 'refs/heads/staging' }}
            # Semantic versions (for releases)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image (Production - main branch)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./tea_frontend
          file: ./tea_frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_APP_CLIENT_ID=${{ secrets.GH_APP_CLIENT_ID }}
            GITHUB_APP_CLIENT_SECRET=${{ secrets.GH_APP_CLIENT_SECRET }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            API_URL=${{ secrets.API_URL_MAIN }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL_MAIN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build and push Docker image (Staging branch)
        if: github.ref == 'refs/heads/staging'
        uses: docker/build-push-action@v5
        with:
          context: ./tea_frontend
          file: ./tea_frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_APP_CLIENT_ID=${{ secrets.GH_APP_CLIENT_ID_STAGING }}
            GITHUB_APP_CLIENT_SECRET=${{ secrets.GH_APP_CLIENT_SECRET_STAGING }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET_STAGING }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL_STAGING }}
            API_URL=${{ secrets.API_URL_STAGING }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL_STAGING }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build and push Docker image (PR/other branches)
        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/staging'
        uses: docker/build-push-action@v5
        with:
          context: ./tea_frontend
          file: ./tea_frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GITHUB_APP_CLIENT_ID=${{ secrets.GH_APP_CLIENT_ID_STAGING }}
            GITHUB_APP_CLIENT_SECRET=${{ secrets.GH_APP_CLIENT_SECRET_STAGING }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET_STAGING }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL_STAGING }}
            API_URL=${{ secrets.API_URL_STAGING }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL_STAGING }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
