import { describe, expect, it } from "vitest";
import type { CaseExportNested, TreeNode } from "@/lib/schemas/case-export";
import { MarkdownExporter } from "../exporters/markdown-exporter";
import type { RenderedDocument, RenderedSection } from "../types";

/**
 * Sample tree node for testing
 */
function createSampleTree(): TreeNode {
	return {
		id: "goal-1",
		type: "GOAL",
		name: "G1",
		description: "Top-level goal description",
		inSandbox: false,
		context: ["Operating environment", "Regulatory context"],
		assumption: "Normal operating conditions",
		justification: "Based on risk analysis",
		children: [
			{
				id: "evidence-1",
				type: "EVIDENCE",
				name: "E1",
				description: "Evidence supporting the goal",
				url: "https://example.com/evidence",
				inSandbox: false,
				children: [],
			},
		],
		comments: [
			{
				author: "testuser",
				content: "This is a test comment",
				createdAt: "2024-01-15T10:00:00Z",
			},
		],
	};
}

/**
 * Create a minimal rendered document for testing
 */
function createSampleDocument(): RenderedDocument {
	return {
		metadata: {
			caseName: "Test Case",
			caseDescription: "A test assurance case",
			exportedAt: "2024-01-15T10:00:00Z",
			version: "1.0",
			elementCount: 5,
			format: "markdown",
		},
		branding: {
			primaryColour: "#1e40af",
			secondaryColour: "#64748b",
			footerText: "Generated by TEA Platform",
			fontFamily: "Inter, sans-serif",
			organisationName: "Test Organisation",
		},
		sections: [],
	};
}

describe("MarkdownExporter", () => {
	const exporter = new MarkdownExporter();

	describe("exporter properties", () => {
		it("should have correct format", () => {
			expect(exporter.format).toBe("markdown");
		});

		it("should have correct MIME type", () => {
			expect(exporter.mimeType).toBe("text/markdown");
		});

		it("should have correct file extension", () => {
			expect(exporter.fileExtension).toBe("md");
		});
	});

	describe("export method", () => {
		it("should export a document successfully", async () => {
			const document = createSampleDocument();
			const result = await exporter.export(document, { caseName: "Test Case" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("# Test Case");
				expect(result.filename).toMatch(/^test-case-\d{4}-\d{2}-\d{2}\.md$/);
				expect(result.mimeType).toBe("text/markdown");
			}
		});

		it("should include YAML frontmatter", async () => {
			const document = createSampleDocument();
			const result = await exporter.export(document, { caseName: "Test Case" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("---");
				expect(result.content).toContain('title: "Test Case"');
				expect(result.content).toContain('description: "A test assurance case"');
				expect(result.content).toContain('generator: "TEA Platform"');
				expect(result.content).toContain('organisation: "Test Organisation"');
			}
		});

	});

	describe("section rendering", () => {
		it("should render heading blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "goals",
					title: "Goals",
					blocks: [{ type: "heading", level: 3, text: "Goal Section" }],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("## Goals");
				expect(result.content).toContain("### Goal Section");
			}
		});

		it("should render paragraph blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "executive-summary",
					title: "Summary",
					blocks: [{ type: "paragraph", text: "This is a summary paragraph." }],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("This is a summary paragraph.");
			}
		});

		it("should render unordered list blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "metadata",
					title: "Details",
					blocks: [
						{
							type: "list",
							ordered: false,
							items: ["Item one", "Item two", "Item three"],
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("- Item one");
				expect(result.content).toContain("- Item two");
				expect(result.content).toContain("- Item three");
			}
		});

		it("should render ordered list blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "metadata",
					title: "Steps",
					blocks: [
						{
							type: "list",
							ordered: true,
							items: ["First step", "Second step"],
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("1. First step");
				expect(result.content).toContain("2. Second step");
			}
		});

		it("should render table blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "evidence",
					title: "Evidence",
					blocks: [
						{
							type: "table",
							headers: ["Name", "URL", "Description"],
							rows: [["E1", "https://example.com", "Test evidence"]],
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("| Name | URL | Description |");
				expect(result.content).toContain("| --- | --- | --- |");
				expect(result.content).toContain(
					"| E1 | https://example.com | Test evidence |"
				);
			}
		});

		it("should escape pipe characters in table cells", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "metadata",
					title: "Data",
					blocks: [
						{
							type: "table",
							headers: ["Key", "Value"],
							rows: [["OR condition", "A | B"]],
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("A \\| B");
			}
		});

		it("should render divider blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "metadata",
					title: "Section",
					blocks: [
						{ type: "paragraph", text: "Before" },
						{ type: "divider" },
						{ type: "paragraph", text: "After" },
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("Before");
				expect(result.content).toContain("---");
				expect(result.content).toContain("After");
			}
		});

		it("should render metadata blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "metadata",
					title: "Metadata",
					blocks: [{ type: "metadata", key: "Version", value: "1.0.0" }],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("**Version:** 1.0.0");
			}
		});

		it("should render image blocks with src", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "diagram",
					title: "Diagram",
					blocks: [
						{
							type: "image",
							src: "data:image/png;base64,abc123",
							alt: "Case diagram",
							caption: "Figure 1: Case structure",
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain(
					"![Case diagram](data:image/png;base64,abc123)"
				);
				expect(result.content).toContain("*Figure 1: Case structure*");
			}
		});

		it("should render image blocks without src as placeholder", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "diagram",
					title: "Diagram",
					blocks: [{ type: "image", src: "", alt: "Missing image" }],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("*[Image: Missing image]*");
			}
		});
	});

	describe("element rendering", () => {
		it("should render element blocks with all fields", async () => {
			const tree = createSampleTree();
			const document = createSampleDocument();
			document.sections = [
				{
					type: "goals",
					title: "Goals",
					blocks: [{ type: "element", node: tree, depth: 0 }],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				// Title
				expect(result.content).toContain("### Goal: G1");
				// Description
				expect(result.content).toContain("Top-level goal description");
				// Context
				expect(result.content).toContain("**Context:**");
				expect(result.content).toContain("- Operating environment");
				expect(result.content).toContain("- Regulatory context");
				// Assumption
				expect(result.content).toContain(
					"**Assumption:** Normal operating conditions"
				);
				// Justification
				expect(result.content).toContain(
					"**Justification:** Based on risk analysis"
				);
				// Comments
				expect(result.content).toContain("**Comments:**");
				expect(result.content).toContain("**testuser**");
				expect(result.content).toContain("This is a test comment");
			}
		});

		it("should render evidence elements with URL", async () => {
			const evidence: TreeNode = {
				id: "e1",
				type: "EVIDENCE",
				name: "Test Evidence",
				description: "Evidence description",
				url: "https://example.com/doc",
				inSandbox: false,
				children: [],
			};
			const document = createSampleDocument();
			document.sections = [
				{
					type: "evidence",
					title: "Evidence",
					blocks: [{ type: "element", node: evidence, depth: 0 }],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain(
					"**URL:** [https://example.com/doc](https://example.com/doc)"
				);
			}
		});

		it("should indicate sandbox elements as draft", async () => {
			const sandboxElement: TreeNode = {
				id: "s1",
				type: "PROPERTY_CLAIM",
				name: "Draft Claim",
				description: "Work in progress",
				inSandbox: true,
				children: [],
			};
			const document = createSampleDocument();
			document.sections = [
				{
					type: "property-claims",
					title: "Claims",
					blocks: [{ type: "element", node: sandboxElement, depth: 0 }],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("*\\[Draft\\]*");
			}
		});
	});

	describe("special character escaping", () => {
		it("should escape markdown special characters in headings", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "goals",
					title: "Goals *and* Strategies",
					blocks: [
						{ type: "heading", level: 3, text: "Goal [1]: Test *emphasis*" },
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("Goals \\*and\\* Strategies");
				expect(result.content).toContain(
					"Goal \\[1\\]: Test \\*emphasis\\*"
				);
			}
		});

		it("should escape YAML special characters in frontmatter", async () => {
			const document = createSampleDocument();
			document.metadata.caseName = 'Case with "quotes"';
			document.metadata.caseDescription = "Line 1\nLine 2";

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain('title: "Case with \\"quotes\\""');
				expect(result.content).toContain(
					'description: "Line 1\\nLine 2"'
				);
			}
		});
	});

	describe("empty content handling", () => {
		it("should skip empty sections", async () => {
			const document = createSampleDocument();
			document.sections = [
				{ type: "goals", title: "Goals", blocks: [] },
				{
					type: "evidence",
					title: "Evidence",
					blocks: [{ type: "paragraph", text: "Has content" }],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).not.toContain("## Goals");
				expect(result.content).toContain("## Evidence");
			}
		});

		it("should skip empty paragraph blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "metadata",
					title: "Info",
					blocks: [
						{ type: "paragraph", text: "" },
						{ type: "paragraph", text: "   " },
						{ type: "paragraph", text: "Valid content" },
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("Valid content");
			}
		});

		it("should skip empty list blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "metadata",
					title: "Lists",
					blocks: [
						{ type: "list", ordered: false, items: [] },
						{ type: "list", ordered: true, items: ["Has item"] },
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("1. Has item");
			}
		});

		it("should skip empty table blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "metadata",
					title: "Tables",
					blocks: [
						{ type: "table", headers: [], rows: [] },
						{
							type: "table",
							headers: ["Col"],
							rows: [["Value"]],
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).toContain("| Col |");
				expect(result.content).toContain("| Value |");
			}
		});
	});

	describe("title-page section handling", () => {
		it("should not add section heading for title-page type", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "title-page",
					title: "Title Page",
					blocks: [{ type: "paragraph", text: "Case overview" }],
				},
			];

			const result = await exporter.export(document, { caseName: "Test" });

			expect(result.success).toBe(true);
			if (result.success && "content" in result) {
				expect(result.content).not.toContain("## Title Page");
				expect(result.content).toContain("Case overview");
			}
		});
	});
});
