import { describe, expect, it } from "vitest";
import { PDFExporter } from "../exporters/pdf-exporter";
import type { RenderedDocument, RenderedSection } from "../types";

/**
 * Create a minimal rendered document for testing
 */
function createSampleDocument(): RenderedDocument {
	return {
		metadata: {
			caseName: "Test Case",
			caseDescription: "A test assurance case",
			exportedAt: "2024-01-15T10:00:00Z",
			version: "1.0",
			elementCount: 5,
			format: "pdf",
		},
		branding: {
			primaryColour: "#1e40af",
			secondaryColour: "#64748b",
			footerText: "Generated by TEA Platform",
			fontFamily: "Inter, sans-serif",
			organisationName: "Test Organisation",
		},
		sections: [],
	};
}

/**
 * Create a section with content blocks for testing
 */
function createSampleSection(): RenderedSection {
	return {
		type: "overview",
		title: "Overview",
		blocks: [
			{ type: "heading", level: 1, text: "Test Heading" },
			{ type: "paragraph", text: "This is a test paragraph." },
			{
				type: "list",
				ordered: false,
				items: ["Item 1", "Item 2", "Item 3"],
			},
			{
				type: "table",
				headers: ["Name", "Value"],
				rows: [
					["First", "100"],
					["Second", "200"],
				],
			},
		],
	};
}

describe("PDFExporter", () => {
	const exporter = new PDFExporter();

	describe("exporter properties", () => {
		it("should have correct format", () => {
			expect(exporter.format).toBe("pdf");
		});

		it("should have correct MIME type", () => {
			expect(exporter.mimeType).toBe("application/pdf");
		});

		it("should have correct file extension", () => {
			expect(exporter.fileExtension).toBe("pdf");
		});
	});

	describe("export method", () => {
		it("should export a document successfully", async () => {
			const document = createSampleDocument();
			const result = await exporter.export(document, { caseName: "Test Case" });

			expect(result.success).toBe(true);
			if (result.success && "blob" in result) {
				expect(result.blob).toBeInstanceOf(Blob);
				expect(result.blob.type).toBe("application/pdf");
				expect(result.filename).toMatch(/^test-case-\d{4}-\d{2}-\d{2}\.pdf$/);
				expect(result.mimeType).toBe("application/pdf");
			}
		});

		it("should generate correct filename with timestamp", async () => {
			const document = createSampleDocument();
			const timestamp = new Date("2024-06-15T12:00:00Z");
			const result = await exporter.export(document, {
				caseName: "My Test Case",
				timestamp,
			});

			expect(result.success).toBe(true);
			if (result.success && "filename" in result) {
				expect(result.filename).toBe("my-test-case-2024-06-15.pdf");
			}
		});

		it("should sanitise case name for filename", async () => {
			const document = createSampleDocument();
			const result = await exporter.export(document, {
				caseName: "Test Case With Special!@#Characters",
			});

			expect(result.success).toBe(true);
			if (result.success && "filename" in result) {
				expect(result.filename).toMatch(
					/^test-case-with-special-characters-\d{4}-\d{2}-\d{2}\.pdf$/
				);
			}
		});

		it("should export document with sections", async () => {
			const document = createSampleDocument();
			document.sections = [createSampleSection()];

			const result = await exporter.export(document, { caseName: "Test Case" });

			expect(result.success).toBe(true);
			if (result.success && "blob" in result) {
				expect(result.blob.size).toBeGreaterThan(0);
			}
		});

		it("should include title page section", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "title-page",
					title: "Title Page",
					blocks: [
						{ type: "heading", level: 1, text: "Test Case Report" },
						{ type: "paragraph", text: "Generated for testing purposes." },
					],
				},
				createSampleSection(),
			];

			const result = await exporter.export(document, { caseName: "Test Case" });

			expect(result.success).toBe(true);
			if (result.success && "blob" in result) {
				expect(result.blob.size).toBeGreaterThan(0);
			}
		});

		it("should handle empty sections", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "overview",
					title: "Empty Section",
					blocks: [],
				},
			];

			const result = await exporter.export(document, { caseName: "Test Case" });

			expect(result.success).toBe(true);
		});

		it("should handle document with branding logo", async () => {
			const document = createSampleDocument();
			document.branding.logoBase64 =
				"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";

			const result = await exporter.export(document, { caseName: "Test Case" });

			expect(result.success).toBe(true);
		});
	});

	describe("content block rendering", () => {
		it("should render heading blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "overview",
					title: "Overview",
					blocks: [
						{ type: "heading", level: 1, text: "Heading 1" },
						{ type: "heading", level: 2, text: "Heading 2" },
						{ type: "heading", level: 3, text: "Heading 3" },
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test Case" });
			expect(result.success).toBe(true);
		});

		it("should render list blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "overview",
					title: "Overview",
					blocks: [
						{
							type: "list",
							ordered: false,
							items: ["Unordered item 1", "Unordered item 2"],
						},
						{
							type: "list",
							ordered: true,
							items: ["Ordered item 1", "Ordered item 2"],
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test Case" });
			expect(result.success).toBe(true);
		});

		it("should render table blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "overview",
					title: "Overview",
					blocks: [
						{
							type: "table",
							headers: ["Column 1", "Column 2", "Column 3"],
							rows: [
								["A1", "B1", "C1"],
								["A2", "B2", "C2"],
							],
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test Case" });
			expect(result.success).toBe(true);
		});

		it("should render divider blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "overview",
					title: "Overview",
					blocks: [
						{ type: "paragraph", text: "Before divider" },
						{ type: "divider" },
						{ type: "paragraph", text: "After divider" },
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test Case" });
			expect(result.success).toBe(true);
		});

		it("should render metadata blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "overview",
					title: "Overview",
					blocks: [
						{ type: "metadata", key: "Author", value: "Test User" },
						{ type: "metadata", key: "Date", value: "2024-01-15" },
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test Case" });
			expect(result.success).toBe(true);
		});

		it("should render element blocks", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "goals",
					title: "Goals",
					blocks: [
						{
							type: "element",
							depth: 0,
							node: {
								id: "goal-1",
								type: "GOAL",
								name: "G1",
								description: "Main goal description",
								inSandbox: false,
								context: ["Context 1", "Context 2"],
								assumption: "Test assumption",
								justification: "Test justification",
								children: [],
							},
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test Case" });
			expect(result.success).toBe(true);
		});

		it("should render evidence element with URL", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "evidence",
					title: "Evidence",
					blocks: [
						{
							type: "element",
							depth: 0,
							node: {
								id: "evidence-1",
								type: "EVIDENCE",
								name: "E1",
								description: "Evidence description",
								url: "https://example.com/evidence",
								inSandbox: false,
								children: [],
							},
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test Case" });
			expect(result.success).toBe(true);
		});

		it("should render element with comments", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "goals",
					title: "Goals",
					blocks: [
						{
							type: "element",
							depth: 0,
							node: {
								id: "goal-1",
								type: "GOAL",
								name: "G1",
								description: "Goal with comments",
								inSandbox: false,
								children: [],
								comments: [
									{
										author: "testuser",
										content: "This is a comment",
										createdAt: "2024-01-15T10:00:00Z",
									},
								],
							},
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test Case" });
			expect(result.success).toBe(true);
		});

		it("should render draft element with sandbox indicator", async () => {
			const document = createSampleDocument();
			document.sections = [
				{
					type: "goals",
					title: "Goals",
					blocks: [
						{
							type: "element",
							depth: 0,
							node: {
								id: "goal-1",
								type: "GOAL",
								name: "G1",
								description: "Draft goal",
								inSandbox: true,
								children: [],
							},
						},
					],
				},
			];

			const result = await exporter.export(document, { caseName: "Test Case" });
			expect(result.success).toBe(true);
		});
	});
});
