# Generated by Django 3.2.8 on 2022-05-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assurancecase",
            name="edit_groups",
            field=models.ManyToManyField(related_name="editable_cases", to="api.EAPGroup"),
        ),
        migrations.AddField(
            model_name="assurancecase",
            name="view_groups",
            field=models.ManyToManyField(related_name="viewable_cases", to="api.EAPGroup"),
        ),
    ]
