# Generated by Django 3.2.8 on 2023-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_eapuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eapuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
