# Generated by Django 3.2.8 on 2023-10-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_propertyclaim_strategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyclaim",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_claims",
                to="api.strategy",
            ),
        ),
    ]
