# Generated by Django 3.2.8 on 2023-10-13 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_eapuser_auth_provider"),
        ("api", "0008_alter_propertyclaim_strategy"),
    ]

    operations = []
