# Generated by Django 3.2.8 on 2023-10-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_assurancecase_color_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assurancecase",
            name="color_profile",
            field=models.CharField(
                blank=True, default="default", max_length=200, null=True
            ),
        ),
    ]
