# Generated by Django 3.2.8 on 2024-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_githubrepository"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="long_description",
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="short_description",
            field=models.CharField(max_length=1000),
        ),
    ]
