# Generated by Django 3.2.8 on 2024-07-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_auto_20240703_0831"),
    ]

    operations = [
        migrations.AlterField(
            model_name="context",
            name="goal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context",
                to="api.toplevelnormativegoal",
            ),
        ),
    ]
