# Generated by Django 3.2.8 on 2024-07-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20240704_1601"),
        ("api", "0018_alter_context_goal"),
    ]

    operations = []
