# Generated by Django 3.2.8 on 2024-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_strategy_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="eapuser",
            name="auth_username",
            field=models.CharField(default="", max_length=200),
        ),
    ]
