# Generated by Django 3.2.8 on 2025-01-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_toplevelnormativegoal_assumption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toplevelnormativegoal",
            name="assumption",
            field=models.TextField(blank=True, null=True),
        ),
    ]
