# Generated by Django 3.2.8 on 2025-01-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_alter_toplevelnormativegoal_assumption"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyclaim",
            name="assumption",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="strategy",
            name="assumption",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="strategy",
            name="justification",
            field=models.TextField(blank=True, default=""),
        ),
    ]
