# Generated by Django 3.2.8 on 2025-03-06 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0037_publishedassurancecase"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudyFeatureImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="case_study_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case_study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_image",
                        to="api.casestudy",
                    ),
                ),
            ],
        ),
    ]
