# Generated by Django 3.2.8 on 2025-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_casestudy_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="assurancecase",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
