# Generated by Django 3.2.8 on 2025-07-10 13:00
# Step 1: Add new field for PublishedAssuranceCase relationship

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_publishedassurancecase_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="published_assurance_cases",
            field=models.ManyToManyField(
                blank=True,
                to="api.PublishedAssuranceCase",
                help_text="New field to replace assurance_cases with UUID relationship",
            ),
        ),
    ]
