# Generated by Django 3.2.8 on 2025-07-10 13:00
# Step 4: Rename the new field back to the original name

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0046_remove_old_assurance_cases"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casestudy",
            old_name="published_assurance_cases",
            new_name="assurance_cases",
        ),
    ]
