name: "User Story"
description: "Template for creating user stories in this repository"
labels: "user-story"

body:
  - type: input
    id: user_role
    attributes:
      label: "User Role"
      description: "As a [type of user]"
      placeholder: "e.g., Admin, Customer, Developer"
    validations:
      required: true

  - type: input
    id: goal
    attributes:
      label: "Goal / Desire"
      description: "I want [some goal or desire]"
      placeholder: "e.g., view user activity, manage settings"
    validations:
      required: true

  - type: input
    id: benefit
    attributes:
      label: "Benefit / Reason"
      description: "So that [some benefit]"
      placeholder: "e.g., improve productivity, ensure data security"
    validations:
      required: true

  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Define criteria for successful implementation. Check all that apply."
      options:
        - label: "Criterion 1"
        - label: "Criterion 2"
        - label: "Criterion 3"

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes / Considerations"
      description: "Any additional context, links, screenshots, or other relevant information"
      placeholder: "Add any extra notes here"
