name: User Story
description: Create a new user story.
title: "[User Story]: "
labels: ["user-story"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing a new user story! Please fill out the details below to help us understand your vision.
  - type: input
    id: role
    attributes:
      label: Role
      description: Who is the user for this story?
      placeholder: ex. As a [Admin]
    validations:
      required: true

  - type: input
    id: feature
    attributes:
      label: Desired Feature
      description: What is the feature you would like to have?
      placeholder: I want to [feature description]
    validations:
      required: true

  - type: input
    id: benefit
    attributes:
      label: Benefit
      description: What is the benefit of this feature?
      placeholder: So that I can [benefit description]
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Please describe the conditions that must be met for this story to be considered complete.
      placeholder: |
        **GIVEN** [precondition]
        **AND** [another precondition if necessary]
        **WHEN** [action taken by the user]
        **THEN** [expected outcome]
        **AND** [another outcome if necessary]
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there any other tasks that need to be completed first?
      placeholder: |
        - [ ] Dependency 1 (include issue link)
        - [ ] Dependency 2 (include issue link)
    validations:
      required: false

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical notes, potential challenges, or architectural considerations for implementation?
      placeholder: |
        - Note 1
        - Note 2
    validations:
      required: false

  - type: checkboxes
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: Please confirm the following are completed before this story can be considered done.
      options:
        - label: The feature fulfills all acceptance criteria.
        - label: The code is reviewed and meets team coding standards.
        - label: All unit, integration, and end-to-end tests are passed.
        - label: The feature meets accessibility standards set for the project.
        - label: The code passes the CI/CD pipeline quality controls (style and linting).
        - label: The feature is merged into the main branch.
        - label: The feature is deployed and functional in the QA environment.
        - label: The feature was demonstrated to the team and accepted by the product owner.
