"""
Django settings for tea_backend project.

Generated by 'django-admin startproject' using Django 3.2.8.
Updated for Django 5.1.5 compatibility.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", os.urandom(32))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "on") == "on"

# Keys needed for OAuth
SOCIAL_AUTH_GITHUB_KEY: str | None = os.environ.get("GITHUB_CLIENT_ID")
SOCIAL_AUTH_GITHUB_SECRET: str | None = os.environ.get("GITHUB_CLIENT_SECRET")
REDIRECT_URI = "http://localhost:3000/login"

ALLOWED_HOSTS = [os.environ["WEBSITE_HOSTNAME"]] if "WEBSITE_HOSTNAME" in os.environ else ["*"]

if "FRONTEND_HOSTNAME" in os.environ:
    ALLOWED_HOSTS += [os.environ["FRONTEND_HOSTNAME"]]


AZURE_ACCOUNT_NAME: str | None = os.getenv("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY: str | None = os.getenv("AZURE_ACCOUNT_KEY")

# Conditional storage configuration based on environment
# Use Azure storage only when explicitly enabled and not in testing
USE_AZURE_STORAGE = os.getenv("USE_AZURE_STORAGE", "false").lower() == "true"
TESTING = "test" in sys.argv or os.getenv("TESTING", "false").lower() == "true"

if USE_AZURE_STORAGE and not TESTING and AZURE_ACCOUNT_NAME and AZURE_ACCOUNT_KEY:
    # Production/Azure configuration
    AZURE_CUSTOM_DOMAIN = f"{AZURE_ACCOUNT_NAME}.blob.core.windows.net"
    MEDIA_URL: str = f"https://{AZURE_CUSTOM_DOMAIN}/media/"

    STORAGES = {
        "default": {
            "BACKEND": "tea_backend.azure_storage.AzureMediaStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    # Development/testing configuration (local file storage)
    # This prevents accidental use of production Azure storage in dev/test
    MEDIA_URL = "/media/"

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Set MEDIA_ROOT for both cases
MEDIA_ROOT: Path = BASE_DIR / "mediafiles"

if DEBUG:
    ALLOWED_HOSTS += ["localhost", "127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    "allauth",
    "allauth.socialaccount",
    "allauth.account",
    "channels",
    "corsheaders",
    "api.apps.ApiConfig",
    "tea_backend",
    "websockets",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_social_auth",
    "social_django",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if "CORS_ORIGIN_WHITELIST" in os.environ:
    CORS_ORIGIN_WHITELIST = os.environ["CORS_ORIGIN_WHITELIST"].split(",")
else:
    CORS_ORIGIN_WHITELIST = [
        "http://localhost:3000",
        "http://localhost:8000",
        "http://localhost:8080",
    ]
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = "tea_backend.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # TODO(cgavidia): Can we use IsAuthenticated instead?
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    # "DEFAULT_PERMISSION_CLASSES": [
    #    "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    # ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",  # Default to JSON
        "rest_framework.renderers.BrowsableAPIRenderer",  # Optional for API browser
    ],
}

WSGI_APPLICATION = "tea_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# use sqlite db for tests
if "test" in sys.argv or "test_coverage" in sys.argv:  # Covers regular testing and django-coverage
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "testdb.sqlite3",
        }
    }
else:
    if "DBHOST" not in os.environ:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }
    else:
        # use Postgres for production server, configured via environment vars
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "HOST": os.environ["DBHOST"],
                "NAME": os.environ["DBNAME"],
                "USER": os.environ["DBUSER"],
                "PASSWORD": os.environ["DBPASSWORD"],
            }
        }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "api.EAPUser"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

AUTHENTICATION_BACKENDS = (
    "allauth.account.auth_backends.AuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
    "social_core.backends.github.GithubOAuth2",
)

SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_AUTHENTICATION_METHOD = "username"
ACCOUNT_UNIQUE_EMAIL = False
ACCOUNT_UNIQUE_USERNAME = True

ASGI_APPLICATION = "tea_backend.asgi.application"

CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# dj-rest-auth settings
REST_AUTH = {
    "LOGIN_SERIALIZER": "api.serializers.CustomLoginSerializer",
    "USE_JWT": False,
    "TOKEN_SERIALIZER": "api.serializers.CustomLoginSerializer",
}
