/**
 * Zod schemas for branding configuration.
 *
 * Branding options allow customisation of colours, logos,
 * and organisation details in exported documents.
 */

import { z } from "zod";

/**
 * Hex colour validation pattern
 */
const hexColourPattern = /^#[0-9A-Fa-f]{6}$/;

/**
 * Hex colour schema with validation
 */
const hexColourSchema = z
	.string()
	.regex(hexColourPattern, "Must be a valid hex colour code (e.g., #1a2b3c)")
	.describe("Hex colour code");

/**
 * Branding configuration schema
 */
export const BrandingConfigSchema = z
	.object({
		primaryColour: hexColourSchema
			.default("#1e40af")
			.describe("Primary brand colour for headings and accents"),
		secondaryColour: hexColourSchema
			.default("#64748b")
			.describe("Secondary colour for borders and muted text"),
		logoUrl: z
			.string()
			.url()
			.optional()
			.describe("URL to organisation logo (PNG or SVG)"),
		logoBase64: z
			.string()
			.optional()
			.describe("Base64-encoded logo image (alternative to URL)"),
		organisationName: z
			.string()
			.optional()
			.describe("Organisation name displayed on title page"),
		footerText: z
			.string()
			.default("Generated by TEA Platform")
			.describe("Footer text for each page"),
		fontFamily: z
			.string()
			.default("Inter, sans-serif")
			.describe("Primary font family for the document"),
	})
	.describe("Branding and visual styling options for exported documents");

export type BrandingConfig = z.infer<typeof BrandingConfigSchema>;

/**
 * Default branding values
 */
export const DEFAULT_BRANDING: Required<
	Pick<
		BrandingConfig,
		"primaryColour" | "secondaryColour" | "footerText" | "fontFamily"
	>
> = {
	primaryColour: "#1e40af",
	secondaryColour: "#64748b",
	footerText: "Generated by TEA Platform",
	fontFamily: "Inter, sans-serif",
};

/**
 * Resolve branding config with defaults applied
 */
export function resolveBranding(
	config?: Partial<BrandingConfig>
): BrandingConfig {
	return {
		primaryColour: config?.primaryColour ?? DEFAULT_BRANDING.primaryColour,
		secondaryColour:
			config?.secondaryColour ?? DEFAULT_BRANDING.secondaryColour,
		logoUrl: config?.logoUrl,
		logoBase64: config?.logoBase64,
		organisationName: config?.organisationName,
		footerText: config?.footerText ?? DEFAULT_BRANDING.footerText,
		fontFamily: config?.fontFamily ?? DEFAULT_BRANDING.fontFamily,
	};
}
