/**
 * Enhanced React Flow Components
 *
 * Main export point for all enhanced React Flow components including nodes,
 * handles, and utilities. Inspired by FloraFauna.ai interface design.
 *
 * @module enhanced
 */

// Node Components
export {
  BaseNode,
  BaseNodeWithActions,
  BaseNodeWithMetadata,
  CompactBaseNode,
  LargeBaseNode,
  CollapsibleNode,
  FocusCollapsibleNode,
  ProgressiveCollapsibleNode,
  ControlledCollapsibleNode,
  MemoizedCollapsibleNode,
  NodeStateManager,
  NodeStateControls,
  useNodeStateContext,
  useNodeStateWithFlow,
  withNodeState,
  useNodeState,
} from './nodes';

// Handle Components
export {
  CustomHandle,
  CustomHandleWithIndicator,
  PulsingHandle,
  CustomHandleWithTooltip,
} from './handles';

// Edge Components
export {
  AnimatedEdge,
  FastAnimatedEdge,
  SlowAnimatedEdge,
  PulseAnimatedEdge,
  GlowAnimatedEdge,
  ThicknessAnimatedEdge,
  GradientEdge,
  RainbowGradientEdge,
  PulsingGradientEdge,
  RadialGradientEdge,
  ShimmerGradientEdge,
  TemperatureGradientEdge,
  GlowingEdge,
  NeonEdge,
  SoftGlowEdge,
  IntenseGlowEdge,
  ActiveDataFlowEdge,
  ErrorGlowEdge,
  SuccessGlowEdge,
  WarningGlowEdge,
  BreathingGlowEdge,
  FlowingEdge,
  FastFlowEdge,
  SlowFlowEdge,
  HeavyTrafficEdge,
  LightTrafficEdge,
  BidirectionalFlowEdge,
  DataStreamEdge,
  PulseFlowEdge,
  TrailFlowEdge,
  SmartEdge,
  StrongConnectionEdge,
  WeakConnectionEdge,
  TypedSmartEdge,
  DependencyEdge,
  InheritanceEdge,
  AssociationEdge,
  AdaptivePathEdge,
  InfoEdge,
  ActivityEdge,
  edgeTypes,
  defaultEdgeOptions,
  edgeStylePresets,
  applyEdgePreset,
  createEdge,
  createEdges,
} from './edges';

// Interaction Components
export {
  DoubleClickHandler,
  useDoubleClickHandler,
  withDoubleClickHandler,
  NodeCreator,
  useNodeCreator,
  NodeTypeSelector,
  CompactNodeTypeSelector,
  NodePositioner,
  useNodePositioner,
  // Creation utilities
  generateNodeId,
  screenToFlowPosition,
  snapToGrid,
  calculateDistance,
  checkPositionOverlap,
  findNonOverlappingPosition,
  calculateSmartPosition,
  getDefaultNodeData,
  createNodeObject,
  getRecentNodeTypes,
  validateNodeCreation,
  calculateConnectionHints,
  getNodeTemplates,
  saveRecentTypes,
  loadRecentTypes,
  saveCreationPreferences,
  loadCreationPreferences,
  debounce,
} from './interactions';

// Utility Functions
export {
  // Theme Configuration
  themeConfig,
  backgroundColors,
  textColors,
  iconColors,
  borderColors,
  nodeTypeConfig,
  animationTimings,
  nodeAnimationVariants,
  collapseAnimationVariants,
  handleStyleConfig,
  glassmorphismPresets,
  getNodeTypeConfig,
  getColorSchemeClasses,
  getNodeIcon,
  buildNodeClasses,

  // Node Styling Utilities
  nodeStyles,
  buildNodeContainerClasses,
  buildNodeHeaderClasses,
  buildNodeTitleClasses,
  buildNodeIconClasses,
  buildNodeContentClasses,
  buildPreviewTextClasses,
  buildDescriptionClasses,
  buildSeparatorClasses,
  getIconSize,
  getShadowClass,
  getBorderRadiusClass,
  applyGlassmorphism,
  buildCustomGlassmorphism,
  buildHoverClasses,
  buildFocusClasses,
  buildSelectedClasses,
  buildInteractionClasses,
  buildFlexClasses,
  buildResponsiveWidthClasses,

  // Animation Utilities
  animations,
  nodeEntranceVariants,
  nodeFadeVariants,
  nodeScaleVariants,
  contentCollapseVariants,
  sectionSlideVariants,
  hoverVariants,
  iconHoverVariants,
  buttonPressVariants,
  staggerContainerVariants,
  fastStaggerContainerVariants,
  slowStaggerContainerVariants,
  staggerItemVariants,
  handleDecoratorVariants,
  handlePulseVariants,
  selectionVariants,
  selectionRingVariants,
  modalBackdropVariants,
  modalContentVariants,
  createSpringTransition,
  createEaseTransition,
  createStaggerTransition,
  combineVariants,
  createRevealAnimation,
  getAnimationPreset,
  prefersReducedMotion,
  withReducedMotion,
} from './utils';

// Demo Components
export {
  CollapsibleNodeDemo,
  IntegrationExample,
  EnhancedInteractiveCaseViewer,
} from './demos';

// Edge Demo Components
export { default as EdgeDemo, SimpleEdgeShowcase } from './edges/EdgeDemo';

// Interaction Demo Components
export { default as NodeCreationDemo, SimpleNodeCreationDemo } from './interactions/NodeCreationDemo';

// Menu Components (Context Menus)
export {
  // Base Components
  ContextMenu,
  useContextMenu,
  withContextMenu,
  ContextMenuProvider,
  ContextMenuContext,
  useContextMenuContext,
  ContextMenuTrigger,
  useDebounceContextMenu,
  // Menu Items
  MenuItem,
  MenuSeparator,
  MenuHeader,
  MenuFooter,
  RecentActionsMenu,
  KeyboardShortcutsHint,
  SearchableMenu,
  renderMenuItems,
  MenuItemGroup,
  ConditionalMenuItem,
  // Specific Context Menus
  NodeContextMenu,
  useNodeContextMenu,
  NodeContextMenuWrapper,
  withNodeContextMenu,
  getNodeTypeLabel,
  getNodeTypeColor,
  EdgeContextMenu,
  useEdgeContextMenu,
  EdgeContextMenuWrapper,
  withEdgeContextMenu,
  getEdgeTypeLabel,
  getEdgeStylePresets,
  applyEdgeStylePreset,
  CanvasContextMenu,
  useCanvasContextMenu,
  CanvasContextMenuWrapper,
  withCanvasContextMenu,
  snapToGrid as menuSnapToGrid,
  isPositionEmpty,
  findOptimalPosition,
  // Configuration and Actions
  nodeMenuConfig,
  edgeMenuConfig,
  canvasMenuConfig,
  multiSelectMenuConfig,
  getNodeMenuConfig,
  getEdgeMenuConfig,
  getCanvasMenuConfig,
  getMultiSelectMenuConfig,
  filterMenuItems,
  menuActions,
  executeAction,
  checkClipboard,
} from './menus';

// Menu Demo Component
export { default as ContextMenuDemo, ContextMenuDemoWrapper } from './menus/ContextMenuDemo';

// Animation System
export {
  // Provider
  AnimationProvider,
  useAnimation,
  useAnimationPerformance,
  useAnimationPreferences,
  // Presets
  TIMING,
  EASING,
  SPRING,
  ENTRY_ANIMATIONS,
  EXIT_ANIMATIONS,
  INTERACTION_ANIMATIONS,
  LOADING_ANIMATIONS,
  COLLAPSE_ANIMATIONS,
  STAGGER_ANIMATIONS,
  EDGE_ANIMATIONS,
  HANDLE_ANIMATIONS,
  NOTIFICATION_ANIMATIONS,
  MODAL_ANIMATIONS,
  PERFORMANCE,
  PRESETS,
  getPreset,
  createCustomPreset,
  mergePresets,
  // Spring Animations
  SpringStaggerContainer,
  SpringStaggerItem,
  SpringScale,
  SpringRotate,
  SpringDraggable,
  SpringScrollTrigger,
  SpringParallax,
  SpringVelocity,
  SpringChain,
  SpringGesture,
  SpringMagnetic,
  SpringInertia,
  SpringKeyframes,
  // Loading States
  Skeleton,
  NodeSkeleton,
  Spinner,
  DotsLoader,
  ProgressBar,
  CircularProgress,
  PulseLoader,
  ShimmerContainer,
  ContentReveal,
  Placeholder,
  CardSkeleton,
  LoadingOverlay,
  // Micro Interactions
  InteractiveButton,
  RippleEffect,
  AnimatedFocusRing,
  FeedbackToast,
  SuccessCheckmark,
  AnimatedCounter,
  RotatingIcon,
  BounceIcon,
  Shake,
  Wiggle,
  AnimatedTooltip,
  BadgePulse,
  // Transition Effects
  PageTransition,
  ModalTransition,
  TabTransition,
  AccordionTransition,
  CrossfadeTransition,
  SlideTransition,
  MorphTransition,
  CollapseTransition,
  DrawerTransition,
  FadeThroughTransition,
} from './animations';

/**
 * Default export with all modules organized
 */
export default {
  nodes: require('./nodes').default,
  handles: require('./handles').default,
  edges: require('./edges').default,
  interactions: require('./interactions').default,
  menus: require('./menus').default,
  utils: require('./utils').default,
  demos: require('./demos').default,
  animations: require('./animations').default,
};
