// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	teaSidebar: [
		"docs/intro",
		"docs/about",
		{
			type: "category",
			label: "TEA Curriculum",
			collapsible: true,
			collapsed: true,
			items: [
				{
					type: "doc",
					id: "docs/curriculum/index",
				},
				{
					type: "category",
					label: "TEA Trainee",
					collapsible: true,
					collapsed: true,
					items: [
						"docs/curriculum/tea-trainee/index",
						{
							type: "category",
							label: "Module 1: Your First Sip of TEA",
							collapsible: true,
							collapsed: false,
							items: [
								"docs/curriculum/tea-trainee/first-sip/introduction",
								"docs/curriculum/tea-trainee/first-sip/exploration",
								"docs/curriculum/tea-trainee/first-sip/reflection",
								"docs/curriculum/tea-trainee/first-sip/assessment",
								"docs/curriculum/tea-trainee/first-sip/summary",
							],
						},
					],
				},
				{
					type: "category",
					label: "TEA Specialist",
					collapsible: true,
					collapsed: true,
					items: ["docs/curriculum/tea-specialist/index"],
				},
				{
					type: "category",
					label: "TEA Expert",
					collapsible: true,
					collapsed: true,
					items: ["docs/curriculum/tea-expert/index"],
				},
				{
					type: "category",
					label: "Hands-On Resources",
					collapsible: true,
					collapsed: true,
					items: [
						"docs/curriculum/hands-on/index",
						{
							type: "category",
							label: "Case Studies",
							collapsible: true,
							collapsed: true,
							items: [
								"docs/curriculum/case-studies/index",
								"docs/curriculum/case-studies/flood-risk-assessment",
								"docs/curriculum/case-studies/crop-damage-assessment",
								"docs/curriculum/case-studies/diabetic-retinopathy-screening",
								"docs/curriculum/case-studies/student-learning-assessment",
							],
						},
					],
				},
				{
					type: "category",
					label: "Standalone Resources",
					collapsible: true,
					collapsed: true,
					items: [
						"docs/curriculum/standalone/index",
						"docs/curriculum/standalone/standards",
						"docs/curriculum/standalone/assurance-ecosystem",
					],
				},
			],
		},
		{
			type: "category",
			label: "Technical Documentation",
			collapsible: true,
			collapsed: true,
			items: [
				{
					type: "autogenerated",
					dirName: "docs/technical-guide",
				},
			],
		},
		{
			type: "category",
			label: "Community Resources",
			collapsible: true,
			collapsed: true,
			items: [
				{
					type: "autogenerated",
					dirName: "docs/community",
				},
			],
		},
	],
	apiSidebar: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
