const CHANGELOG_URL = "/docs/technical-guide/ci-cd-pipeline/changelog";

/**
 * The table-of-contents heading-depth cap for a docs page, keyed on its URL.
 *
 * Caps to h2/h3 site-wide (F10) — deeper headings (e.g. a page's own nested
 * subsections) made the TOC read as noise rather than a page outline. The
 * changelog is generated by semantic-release and nests an h3 per change type
 * under each h2 version, which is too deep even by that standard, so it caps
 * to h2 only (F11) via this one URL-keyed override rather than editing the
 * generated file.
 */
export function tocDepthForUrl(url: string): number {
	return url === CHANGELOG_URL ? 2 : 3;
}
