# Generated by Django 3.2.8 on 2025-07-04 07:30
# Custom migration to handle integer-to-UUID conversion for many-to-many field
# This replaces the original migrations 0044, 0045, and 0046 with a single safe operation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eap_api", "0043_publishedassurancecase_description"),
    ]

    operations = [
        # First, drop the existing many-to-many table since it's empty
        # This avoids the PostgreSQL type casting error
        migrations.RunSQL(
            "DROP TABLE IF EXISTS eap_api_casestudy_assurance_cases CASCADE;",
            reverse_sql="-- No reverse operation needed"
        ),
        
        # Set the final state: ManyToManyField to PublishedAssuranceCase (UUID)
        # This is the desired end state from migration 0046
        migrations.AlterField(
            model_name="casestudy",
            name="assurance_cases",
            field=models.ManyToManyField(
                blank=True, to="eap_api.PublishedAssuranceCase"
            ),
        ),
    ]