import {
	DocsBody,
	DocsDescription,
	DocsPage,
	DocsTitle,
	EditOnGitHub,
} from "fumadocs-ui/layouts/docs/page";
import { notFound } from "next/navigation";
import { source } from "@/lib/docs-source";
import { getMDXComponents } from "@/mdx-components";

export function generateStaticParams() {
	return source.generateParams();
}

export async function generateMetadata(props: {
	params: Promise<{ slug?: string[] }>;
}) {
	const params = await props.params;
	const page = source.getPage(params.slug);

	if (!page) {
		notFound();
	}

	return {
		title: page.data.title,
		description: page.data.description,
	};
}

export default async function Page(props: {
	params: Promise<{ slug?: string[] }>;
}) {
	const params = await props.params;
	const page = source.getPage(params.slug);

	if (!page) {
		notFound();
	}

	const MDXContent = page.data.body;

	// Cap the table of contents to h2/h3 site-wide (F10) — deeper headings
	// (e.g. a page's own nested subsections) made the TOC read as noise
	// rather than a page outline. The changelog is generated by
	// semantic-release and nests an h3 per change type under each h2
	// version, which is too deep even by that standard, so it caps to h2
	// only (F11) via this per-page override rather than editing the
	// generated file.
	const isChangelog =
		page.url === "/docs/technical-guide/ci-cd-pipeline/changelog";
	const maxTocDepth = isChangelog ? 2 : 3;
	const toc = page.data.toc.filter((item) => item.depth <= maxTocDepth);

	return (
		<DocsPage toc={toc}>
			<DocsTitle>{page.data.title}</DocsTitle>
			<DocsDescription>{page.data.description}</DocsDescription>
			<EditOnGitHub
				className="w-fit self-start"
				href={`https://github.com/alan-turing-institute/AssurancePlatform/tree/main/content/${page.path}`}
			/>
			<DocsBody>
				<MDXContent components={getMDXComponents()} />
			</DocsBody>
		</DocsPage>
	);
}
