name: backend-docker

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Set environment
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Get environment
        shell: bash
        run: |
          echo "sha_short: ${{ env.sha_short }}"
          echo "now: ${{ env.now }}"
          echo "version: ${{ env.now }}.${{ env.sha_short }}"
      - name: "Build main: eap_backend"
        if: ${{ github.ref == 'refs/heads/main' }}
        working-directory: eap_backend
        run: |
          docker build -t turingassuranceplatform/eap_backend:main -f Dockerfile .
          docker push turingassuranceplatform/eap_backend:main
      - name: "Build Docker imager: eap_backend"
        if: ${{ github.ref == 'refs/heads/develop' }}
        working-directory: eap_backend
        run: |
          docker build -t turingassuranceplatform/eap_backend:${{ env.now }}.${{ env.sha_short }} -t turingassuranceplatform/eap_backend:latest -f Dockerfile .
          docker push turingassuranceplatform/eap_backend --all-tags
