name: backend-docker

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: "Build main"
        if: ${{ github.ref == 'refs/heads/main' }}
        working-directory: eap_backend
        run: |
          docker build -t turingassuranceplatform/eap_backend:main -f Dockerfile .
          docker push turingassuranceplatform/eap_backend:main
      - name: "Build develop"
        if: ${{ github.ref == 'refs/heads/develop' }}
        working-directory: eap_backend
        run: |
          docker build -t turingassuranceplatform/eap_backend:develop -f Dockerfile .
          docker push turingassuranceplatform/eap_backend:develop

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Publish main"
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: "eap-backend"
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          images: "turingassuranceplatform/eap_backend:main"
