name: docs-publish
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
  release:
    types:
      - published
permissions:
    contents: write
jobs:
    pre-commit:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: actions/setup-python@v4
              with:
                python-version: "3.x"
            - uses: pre-commit/action@v3.0.0
              with:
                extra_args: --hook-stage manual --all-files
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: 3.x
            - name: "Upgrade pip"
              run: pip install --upgrade pip
            - name: "Install requirements"
              run: pip install -r site/requirements.txt
            - name: "Run jupyterbook"
              run: jupyter-book build docs --all
            - name: Build and Deploy
              working-directory: ./site
              run: |
                mkdocs build
                mkdocs gh-deploy --force
env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true