name: docs-publish
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: "Upgrade pip"
        run: pip install --upgrade pip
      - name: "Install requirements"
        run: pip install -r site/requirements.txt
      - name: Build and Deploy
        working-directory: ./site
        run: |
          mkdocs build
          mkdocs gh-deploy --force
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
